### ISSUE TITLE
Touch pad does not work

### ISSUE THREAD

**Issue by rina2016** [bigsadan/surface-pro-4-hackintosh#1]
While installing MacOS it will behave like a mouse, but gestures such as two fingers will not work.
When restarting after the installation is completed, the touch pad will not respond.
The trackpad setting is displayed in the environment setting.

Attach the debugging file created in gen_debug.sh.

安装MacOS时，它的行为就像一个鼠标，但两个手指等手势将无法正常工作。
安装完成后重新启动时，触摸板不会响应。
触控板设置显示在环境设置中。

附加gen_debug.sh中创建的调试文件。
[debug_9439.zip](https://github.com/bigsadan/surface-pro-4-hackintosh-10.14.3/files/2923873/debug_9439.zip)

**Comment by bigsadan** [comment]
[voodooi2c.zip](https://github.com/bigsadan/surface-pro-4-hackintosh-10.14.3/files/2940123/voodooi2c.zip)
Try this first,  it's an old version that only two fingers works
