### ISSUE TITLE
10.15.7 config.plist update ?

### ISSUE THREAD

**Issue by gityasss** [bigsadan/surface-pro-4-hackintosh#102]
Hi people
i updated my surface book from 10.15.3 to 10.15.7, but the config.plist gives kernel panic even if i change matchos to 10.15.7 ...
anyone succeeded in updating successfully to latest build of catalina ??

**Comment by WONGWAI1017** [comment]
Same issue here, any idea now?

**Comment by gityasss** [comment]
not yet , still waiting for bigsadan to update the files to 10.15.7 ....
