### ISSUE TITLE
Surfacebook1 Working Big Sur Clover 5125

### ISSUE THREAD

**Issue by gityasss** [bigsadan/surface-pro-4-hackintosh#104]
Hi folks !
i managed to install Big Sur on my surface book 1 with clover 5125
enjoy !
ps : to install big sur use configIs.plist and always start from preboot, once installed use config2.plist to boot normally 
[EFI.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/5464553/EFI.zip)

![Screen Shot 2020-10-29 at 15 06 32](https://user-images.githubusercontent.com/63503032/97587241-75df8280-19fb-11eb-80d9-e5212362f4e0.png)

**Comment by samchugit** [comment]
hi @gityasss , is everything works fine? No loopboot or devices not working or some problem?

**Comment by gityasss** [comment]
> hi @gityasss , is everything works fine? No loopboot or devices not working or some problem?

yes its working smooth and fast

**Comment by samchugit** [comment]
hi @gityasss , I tried to install big sur on pro 4 using configIs.plist, but I can't boot the install image. So did you update to big sur or fresh install? and can PRO 4 using your config2.plist?

**Comment by gityasss** [comment]
> hi @gityasss , I tried to install big sur on pro 4 using configIs.plist, but I can't boot the install image. So did you update to big sur or fresh install? and can PRO 4 using your config2.plist?

i did a fresh install with configIs.plist , then used config2.plist for normal boot 
you can update to final release too withouth problems
i have surfacebook 1 , and dont own a surfacepro 4 so i cant tell you if it will work or not

**Comment by samchugit** [comment]
Hi @gityasss , I tried your clover to update to big sur. After updating I use configIs.plist enter the system and rebuild the kext cache. I reboot to normal using config2.plist, but I get a black screen after the apple logo. So have you met this situation before?

**Comment by samchugit** [comment]
> Hi @gityasss , I tried your clover to update to big sur. After updating I use configIs.plist enter the system and rebuild the kext cache. I reboot to normal using config2.plist, but I get a black screen after the apple logo. So have you met this situation before?

BTW, since big sur cannot boot, I try to reinstall. However, I can not even install using configIs.plist. It stuck on apple logo when I try to install it.

**Comment by kksxsyj** [comment]
I tried your clover to install big sur ,but the gpu did not work .

**Comment by samchugit** [comment]
Hi @gityasss . In this post #105, @Shuxianger mentioned that macos has limited dvmt to 64m, but pro4 only has 32m, therefore 'minstolensize' patch is necessory. Since the patch has no bigsur version, it'll fail to boot. 
I know less about the detail, so I wander how you solve it? or due to the hardware difference.

**Comment by drvuxe** [comment]
this EFI doe not work with surface book 1 i7-6600u with DGP 960m model
