### ISSUE TITLE
更新OpenCore0.63后升级big sur无限重启

### ISSUE THREAD

**Issue by Shuxianger** [bigsadan/surface-pro-4-hackintosh#105]
貌似光更新OpenCore到0.63版本也会无限重启

**Comment by gityasss** [comment]
> 貌似光更新OpenCore到0.63版本也会无限重启

we still dont have opencore for big sur yet , we are waiting for someone to share his EFI  here 
but you can use clover 5125 to install big sur withouth problems

**Comment by Shuxianger** [comment]
> > [打开核心0.63][打开核心]
> 
> 我们仍然还没有开放核心的大 sur， 我们正在等待有人在这里分享他的
> Efi， 但你可以使用三叶草 5125 安装大 sur 没有问题

**Comment by Shuxianger** [comment]
> > 貌似光更新OpenCore到0.63版本也会无限重启
> 
> we still dont have opencore for big sur yet , we are waiting for someone to share his EFI here
> but you can use clover 5125 to install big sur withouth problems

我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作

**Comment by gityasss** [comment]
> 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作

yes we wait for someone to update this thread to big sur

**Comment by Shuxianger** [comment]
> > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> 
> yes we wait for someone to update this thread to big sur

我在尝试用OC启动系统，Clover怎么做
都无法成功驱动hd540

**Comment by gityasss** [comment]
> > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > 
> > 
> > yes we wait for someone to update this thread to big sur
> 
> 我在尝试用OC启动系统，Clover怎么做
> 都无法成功驱动hd540

I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126

**Comment by Shuxianger** [comment]
> > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > > 
> > > 
> > > yes we wait for someone to update this thread to big sur
> > 
> > 
> > 我在尝试用OC启动系统，Clover怎么做
> > 都无法成功驱动hd540
> 
> I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126

fuck hd540

**Comment by Shuxianger** [comment]
> > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surfa
> > > 
> > > 
> > > yes we wait for someone to update this thread to big sur
> > 
> > 
> > 我在尝试用OC启动系统，Clover怎么做
> > 都无法成功驱动hd540
> 
> I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126

**Comment by Shuxianger** [comment]
> > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > > 
> > > 
> > > yes we wait for someone to update this thread to big sur
> > 
> > 
> > 我在尝试用OC启动系统，Clover怎么做
> > 都无法成功驱动hd540
> 
> I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126

我用OC0.6.4进入了big sur系统，但是我的hd540没有正常工作

**Comment by gityasss** [comment]
> > > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > > > 
> > > > 
> > > > yes we wait for someone to update this thread to big sur
> > > 
> > > 
> > > 我在尝试用OC启动系统，Clover怎么做
> > > 都无法成功驱动hd540
> > 
> > 
> > I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126
> 
> 我用OC0.6.4进入了big sur系统，但是我的hd540没有正常工作

can you share your opencore efi, I would like to test it on my machine
thanks

**Comment by kksxsyj** [comment]
> > > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > > > 
> > > > 
> > > > yes we wait for someone to update this thread to big sur
> > > 
> > > 
> > > 我在尝试用OC启动系统，Clover怎么做
> > > 都无法成功驱动hd540
> > 
> > 
> > I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126
> 
> 我用OC0.6.4进入了big sur系统，但是我的hd540没有正常工作
老哥，能分享一下你的efi吗？我安装好重建缓存后就怎么都进不去系统了。

**Comment by Shuxianger** [comment]
> > > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > > > 
> > > > 
> > > > yes we wait for someone to update this thread to big sur
> > > 
> > > 
> > > 我在尝试用OC启动系统，Clover怎么做
> > > 都无法成功驱动hd540
> > 
> > 
> > I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126
> 
> 我用OC0.6.4进入了big sur系统，但是我的hd540没有正常工作
> 老哥，能分享一下你的efi吗？我安装好重建缓存后就怎么都进不去系统了。

加下我QQ，2412887718

**Comment by samchugit** [comment]
> 加下我QQ，2412887718

你可以直接打包传到这里

**Comment by Shuxianger** [comment]
> > 加下我QQ，2412887718
> 
> 你可以直接打包传到这里

没有梯子，上传不了，上面那个歪果仁老哥我都不敢回

**Comment by Shuxianger** [comment]
> > > > > > 我试了安装big sur，但是成功安装进系统之后会黑屏，也许是我的surface pro4是i7版的问题，HD540没法正常工作
> > > > > 
> > > > > 
> > > > > yes we wait for someone to update this thread to big sur
> > > > 
> > > > 
> > > > 我在尝试用OC启动系统，Clover怎么做
> > > > 都无法成功驱动hd540
> > > 
> > > 
> > > I have surface book 1 with Intel HD 520 i5 6300u working fine on big sur with clover 5126
> > 
> > 
> > 我用OC0.6.4进入了big sur系统，但是我的hd540没有正常工作
> 
> can you share your opencore efi, I would like to test it on my machine
> thanks

你能用hackintool看看你的显示器接口图给我看看吗

**Comment by Shuxianger** [comment]
> > 加下我QQ，[2412887718](tel:2412887718)
> 
> 你可以直接打包传到这里

你的系统能正常启动吗，我想看看你的hackintool里的显示接口配置

**Comment by samchugit** [comment]
不能，黑屏

**Comment by Shuxianger** [comment]
> 不能，黑屏

我要找个能正常启动的，看看hackintool的配置和ior里的配置，然后才能搞定这个黑屏问题了

**Comment by Shuxianger** [comment]
> 不能，黑屏

我已经找到问题了，mac默认将dvmt最小值限制到了64m，但是机器只有32m，而且不能进bios调整dvmt大小，所以就要打一个minstolensize的补丁，现在这个补丁还没有bigsur版的，所以才会黑屏进不去，如果你装的是bigsur的话，可以不用再试了，如果不是的话可以找对应系统版本的minstolensize补丁打上就可以正常启动了

**Comment by Shuxianger** [comment]
> 不能，黑屏

问题已经解决了，可以看我最新开的issues
