### ISSUE TITLE
已经装好10.14.3怎么直接升级到10.14.5

### ISSUE THREAD

**Issue by josangmi** [bigsadan/surface-pro-4-hackintosh#11]
已经装好10.14.3怎么直接升级到10.14.5，是先升级clover 然后把 10.14.5的clover 复制到efi然后从系统升级吗？

**Comment by bigsadan** [comment]
先在10.14.3升级10.14.5，再替换CLOVER文件，替换就等于升级了CLOVER了，用install进去，重建缓存后再切换到新的config.plist。

**Comment by deadfoxwang** [comment]
升級之後進不去了，是把最新的clover 裡面文件全部覆蓋過去嗎？ 直接花屏了。。你的clover文件還要再覆蓋回去嗎？

**Comment by bigsadan** [comment]
不要覆盖，把原来的CLOVER文件夹删除掉，使用新的，再用config-install进入系统重建缓存。

**Comment by deadfoxwang** [comment]
用了 config install進入系統，創建緩存，但是 之前的config 還是進不去，提示 panic
用戶config install 可以進去 ，改不了分辨率

config要重新配？

**Comment by bigsadan** [comment]
不用原来的config啊，新的clover里有新的config.plist，不能用吗？

**Comment by deadfoxwang** [comment]
[https://github.com/Dids/clover-builder/releases/tag/v2.4k_r4979](url)
我在這個裡下載的 不行， 「新的clover新的config.plist」 是指？
我升級之前，10.14.3的時候，用config.plist也進不去，inject EDID才可以進去，但是升級之後 進不去了

**Comment by deadfoxwang** [comment]
對不起，第一次弄這個，被搞暈了了，剛看到你的update，已經OK，真是非常感謝🙏

**Comment by deadfoxwang** [comment]
> 不用原来的config啊，新的clover里有新的config.plist，不能用吗？

不好意思，我發現 聲卡和觸摸板 沒有驅動起來，是不是我遺漏了什麼？之前是可以的

**Comment by josangmi** [comment]
一切都很顺利，就是1600 * 1066  的后面没有闪电箭头，这个要紧不。

**Comment by bigsadan** [comment]
> 一切都很顺利，就是1600 * 1066 的后面没有闪电箭头，这个要紧不。

没有闪电箭头就不是HIDPI，显示模糊，无法接受啊。。。

**Comment by deadfoxwang** [comment]
> > 一切都很顺利，就是1600 * 1066 的后面没有闪电箭头，这个要紧不。
> 
> 没有闪电箭头就不是HIDPI，显示模糊，无法接受啊。。。

我的1600*1066 也不是的，我选了 1368*912 ， 感觉不错。

另外，我的声卡，不知道为什么有时候可以驱动，有时候不可以。 这个是什么原因啊？

**Comment by bigsadan** [comment]
> > > 一切都很顺利，就是1600 * 1066 的后面没有闪电箭头，这个要紧不。
> > 
> > 
> > 没有闪电箭头就不是HIDPI，显示模糊，无法接受啊。。。
> 
> 我的1600 * 1066 也不是的，我选了 1368 * 912 ， 感觉不错。
> 
> 另外，我的声卡，不知道为什么有时候可以驱动，有时候不可以。 这个是什么原因啊？

使用1600x1066 hidpi参照我上一次更新文件夹里，里面有修改好的显示文件，只需要把文件夹及文件名修改成你机器的productId，VendorID就行了。
声卡的话有时可以驱动有时候不可以，是不是睡眠唤醒造成的，可以去https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/   下载新的codecommander，放入S/L/E重建缓存，或者clover中KEXT文件也可以

**Comment by josangmi** [comment]
居然我们的pid和vid一模一样，直接使用了。有小闪电了，很溜。感谢。

**Comment by deadfoxwang** [comment]
> > > > 一切都很顺利，就是1600 * 1066 的后面没有闪电箭头，这个要紧不。
> > > 
> > > 
> > > 没有闪电箭头就不是HIDPI，显示模糊，无法接受啊。。。
> > 
> > 
> > 我的1600 * 1066 也不是的，我选了 1368 * 912 ， 感觉不错。
> > 另外，我的声卡，不知道为什么有时候可以驱动，有时候不可以。 这个是什么原因啊？
> 
> 使用1600x1066 hidpi参照我上一次更新文件夹里，里面有修改好的显示文件，只需要把文件夹及文件名修改成你机器的productId，VendorID就行了。
> 声卡的话有时可以驱动有时候不可以，是不是睡眠唤醒造成的，可以去https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/ 下载新的codecommander，放入S/L/E重建缓存，或者clover中KEXT文件也可以

不是睡醒的时候， 重启或者关机再启动，声卡是有时候可以，有时候不可以。加了 codecommander 也还是不可以。（我是从10.14.3升级到10.14.5的）

**Comment by bigsadan** [comment]
> > > > > 一切都很顺利，就是1600 * 1066 的后面没有闪电箭头，这个要紧不。
> > > > 
> > > > 
> > > > 没有闪电箭头就不是HIDPI，显示模糊，无法接受啊。。。
> > > 
> > > 
> > > 我的1600 * 1066 也不是的，我选了 1368 * 912 ， 感觉不错。
> > > 另外，我的声卡，不知道为什么有时候可以驱动，有时候不可以。 这个是什么原因啊？
> > 
> > 
> > 使用1600x1066 hidpi参照我上一次更新文件夹里，里面有修改好的显示文件，只需要把文件夹及文件名修改成你机器的productId，VendorID就行了。
> > 声卡的话有时可以驱动有时候不可以，是不是睡眠唤醒造成的，可以去https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/ 下载新的codecommander，放入S/L/E重建缓存，或者clover中KEXT文件也可以
> 
> 不是睡醒的时候， 重启或者关机再启动，声卡是有时候可以，有时候不可以。加了 codecommander 也还是不可以。（我是从10.14.3升级到10.14.5的）

我没碰到过也没有其它机友反馈过这个问题，或者和硬件区别有关系，你可以尝试更换appleALC ID看看

**Comment by whiteriche** [comment]
> > > > > > 一切都很顺利，就是1600 * 1066 的后面没有闪电箭头，这个要紧不。
> > > > > 
> > > > > 
> > > > > 没有闪电箭头就不是HIDPI，显示模糊，无法接受啊。。。
> > > > 
> > > > 
> > > > 我的1600 * 1066 也不是的，我选了 1368 * 912 ， 感觉不错。
> > > > 另外，我的声卡，不知道为什么有时候可以驱动，有时候不可以。 这个是什么原因啊？
> > > 
> > > 
> > > 使用1600x1066 hidpi参照我上一次更新文件夹里，里面有修改好的显示文件，只需要把文件夹及文件名修改成你机器的productId，VendorID就行了。


我的是4g 128g版本的。识别不到显示器。只有一种超大的分辨率。按你说的方法不管用，还有别的破解办法吗？
