### ISSUE TITLE
Microsoft Surface Pro Firmware更新破壞opencore的能力（甚至0.6.9）。 請幫忙。 

### ISSUE THREAD

**Issue by billabongbruno** [bigsadan/surface-pro-4-hackintosh#118]
問候，你好嗎？

所以，首先，祝賀你的工作，我很高興你讓一切都完美無缺。

其次，如果翻譯並不完美，我道歉。我是葡萄牙語，我用英語寫了這個，並將它翻譯成你的語言，因為它似乎更加禮貌。

三分之一來，我來這裡要問你的幫助。
所以，我擁有SP4的I5版本，但自從您在Bigsadan的回購工作以來，也許您可以幫助我，我希望。

因此，基本上問題是我的Surface Pro 4決定將自身更新為最新的固件，BigSadan的OpenCore版本低於0.6.6，因此CONFIG.PLIST中沒有殘疾ecurityPolicy標誌。我無法再啟動。微軟打破了.efi加載了一些東西（OpenCore沒有啟動，但Grub工作正常）。
所以現在我無法啟動或安裝任何麥克斯。
我試圖將Bigsadan的版本更新為0.6.9並編輯了Config.plist以確切地匹配並將殘疾人設置為“true”，但即使它沒有啟動，它陷入了Apple徽標。

我甚至嘗試使用您的EFI文件夾並僅編輯Config.Plist來更改該標誌，仍然不起作用。

我嘗試了一組Bigsadan的配置和你的配置，仍然沒有工作。

在這個可怕的固件更新後，您可以在Microsoft強加給我們後進入您的嗎？

你能幫我麼？
所有我的編輯視頻和音樂都在那裡，現在我無法訪問它們。

任何幫助將不勝感激。

此致，
布魯諾。

**Comment by uyhyhg7y** [comment]
我的也是那样了，启动在苹果标志，ran后再也没有反映了，求大神么帮忙啊，以下是我的固件审计以前的引导包
[Uploading EFI-0.zip…]()

**Comment by uyhyhg7y** [comment]
我的也是那样了，启动在苹果标志，ran后再也没有反映了，求大神么帮忙啊，以下是我的固件审计以前的引导包

**Comment by uyhyhg7y** [comment]
我的也是那样了，启动在苹果标志，ran后再也没有反映了，求大神么帮忙啊，以下是我的固件审计以前的引导包

**Comment by uyhyhg7y** [comment]
我的也是那样了，启动在苹果标志，ran后再也没有反映了，求大神么帮忙啊

**Comment by uyhyhg7y** [comment]
[Uploading EFI-0.zip…]()

**Comment by jackjack1-su** [comment]
Enable the SetupVirtualMap quirk

**Comment by gaosld** [comment]
我也一样，在windows下自动更新了五月的fireware后启动黑果卡住，下面是OC的引导日志，求大神分析解决。
[opencore-2021-05-19-023404.txt](https://github.com/bigsadan/surface-pro-4-hackintosh/files/6505563/opencore-2021-05-19-023404.txt)

**Comment by uyhyhg7y** [comment]
SP4的黑果就这样没了？结束了吗？

**Comment by billabongbruno** [comment]
> Enable the SetupVirtualMap quirk

Oh, wow.
Thank you.

This made it finally work.
I hadn't seen it.

**Comment by billabongbruno** [comment]
> SP4的黑果就这样没了？结束了吗？

Yes, it is fixed now.

**Comment by jackjack1-su** [comment]
This is same as the SP7 LOL

**Comment by omarhaya** [comment]
> This is same as the SP7 LOL

Same efi u mean?

**Comment by jackjack1-su** [comment]
Nope. I mean the same issue.
