### ISSUE TITLE
Volume button and Power button not working.

### ISSUE THREAD

**Issue by billabongbruno** [bigsadan/surface-pro-4-hackintosh#119]
Is there any patched .kext or DSDT file that fixes this?

I have OpenCore 0.6.9 and I can't get the volume buttons or the power button to work.
They don't do anything.

是否有任何已修復的.kext或DSDT文件可解決此問題？

 我有OpenCore 0.6.9，但無法使音量按鈕或電源按鈕正常工作。
 他們什麼也沒做。

EDIT:
Fixed it myself, patching my dsdt.aml file and using the ACPIKeyboard.kext

**Comment by uyhyhg7y** [comment]
升级后的SP4又可以支持黑果了？哪位大神可以指导指导吗？

**Comment by omarhaya** [comment]
> Is there any patched .kext or DSDT file that fixes this?
> 
> I have OpenCore 0.6.9 and I can't get the volume buttons or the power button to work.
> They don't do anything.
> 
> 是否有任何已修復的.kext或DSDT文件可解決此問題？
> 
> 我有OpenCore 0.6.9，但無法使音量按鈕或電源按鈕正常工作。
> 他們什麼也沒做。
> 
> EDIT:
> Fixed it myself, patching my dsdt.aml file and using the ACPIKeyboard.kext


Can u share the patch ( config) file plz?

**Comment by billabongbruno** [comment]
> > Is there any patched .kext or DSDT file that fixes this?
> > I have OpenCore 0.6.9 and I can't get the volume buttons or the power button to work.
> > They don't do anything.
> > 是否有任何已修復的.kext或DSDT文件可解決此問題？
> > 我有OpenCore 0.6.9，但無法使音量按鈕或電源按鈕正常工作。
> > 他們什麼也沒做。
> > EDIT:
> > Fixed it myself, patching my dsdt.aml file and using the ACPIKeyboard.kext
> 
> Can u share the patch ( config) file plz?

It won't work unless you have the exact same Surface Pro 4 configuration.
You need to manually edit the dsdt file for your machine.

Besides, it's not only the dsdt.
It's also another .kext and a few minor edits to the config.plist file.

**Comment by uyhyhg7y** [comment]
可以把您的EFI引导发给我试一下嘛发自我的华为手机-------- 原始邮件 --------发件人： billabongbruno ***@***.***>日期： 2021年6月12日周六 早上7:46收件人： bigsadan/surface-pro-4-hackintosh ***@***.***>抄送： Bigbang ***@***.***>, Comment ***@***.***>主    题： Re: [bigsadan/surface-pro-4-hackintosh] Volume button and Power button not working. (#119)





Is there any patched .kext or DSDT file that fixes this?

I have OpenCore 0.6.9 and I can't get the volume buttons or the power button to work.

They don't do anything.

是否有任何已修復的.kext或DSDT文件可解決此問題？

我有OpenCore 0.6.9，但無法使音量按鈕或電源按鈕正常工作。

他們什麼也沒做。

EDIT:

Fixed it myself, patching my dsdt.aml file and using the ACPIKeyboard.kext



Can u share the patch ( config) file plz?



It won't work unless you have the exact same Surface Pro 4 configuration.

You need to manually edit the dsdt file for your machine.

Besides, it's not only the dsdt.

It's also another .kext and a few minor edits to the config.plist file.

**Comment by billabongbruno** [comment]
> 可以把您的EFI引导发给我试一下嘛发自我的华为手机-------- 原始邮件 --------发件人： billabongbruno ***@***.***>日期： 2021年6月12日周六 早上7:46收件人： bigsadan/surface-pro-4-hackintosh ***@***.***>抄送： Bigbang ***@***.***>, Comment ***@***.***>主    题： Re: [bigsadan/surface-pro-4-hackintosh] Volume button and Power button not working. (#119)
> 
> 
> 
> 
> 
> Is there any patched .kext or DSDT file that fixes this?
> 
> I have OpenCore 0.6.9 and I can't get the volume buttons or the power button to work.
> 
> They don't do anything.
> 
> 是否有任何已修復的.kext或DSDT文件可解決此問題？
> 
> 我有OpenCore 0.6.9，但無法使音量按鈕或電源按鈕正常工作。
> 
> 他們什麼也沒做。
> 
> EDIT:
> 
> Fixed it myself, patching my dsdt.aml file and using the ACPIKeyboard.kext
> 
> 
> 
> Can u share the patch ( config) file plz?
> 
> 
> 
> It won't work unless you have the exact same Surface Pro 4 configuration.
> 
> You need to manually edit the dsdt file for your machine.
> 
> Besides, it's not only the dsdt.
> 
> It's also another .kext and a few minor edits to the config.plist file.
> 
> 
> 
> —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

What?
I'm so confused.
