### ISSUE TITLE
sp4  4g版本不识别显示器

### ISSUE THREAD

**Issue by whiteriche** [bigsadan/surface-pro-4-hackintosh#12]
hackintool识别不到显示器。分辨率只有2736@1824一个模式。用过楼主方法还是不行。有别的法子没？

**Comment by bigsadan** [comment]
你用14.3还是14.5，你这描述太过于粗糙。。简直无法排查。。。

**Comment by whiteriche** [comment]
用的10.14.4的镜像，用clover10.14.5安装的。这样有问题吗？现在显示器显示45.5英寸，显存只有19m。

**Comment by bigsadan** [comment]
10.14.4没有用过，你可以直接升到10.14.5，显存19M是显卡没有驱动，理论上，你用install.plist进入系统才会出现这种情况，如果用最终的config.plist，要么进不去卡framebuffer重启，要么成功进入系统驱动显卡，不会出现用config.plist进入系统但只有19m情况。

**Comment by whiteriche** [comment]
好的 我按这个思路再折腾一下。tks 感谢解答。

**Comment by whiteriche** [comment]
我的问题已解决了。
1.10.14.4升级到10.14.5，重建了缓存，用config替代了config-install启动。问题解决了。
2.以前的问题可能是以下因素引起的：重建缓存没有做好。启动的config替换没有做好。重建缓存可以用一行命令行执行，config替代的时候需要彻底删除原先的colver文件，再把最新的拷贝进去。
3.发现外接usb扩展坞的时候，mac重启会进不去系统选择界面，win重启可以。
4.后续需要继续折腾usb网卡问题。

感谢bigsadan耐心解答！

**Comment by bigsadan** [comment]
> 我的问题已解决了。
> 1.10.14.4升级到10.14.5，重建了缓存，用config替代了config-install启动。问题解决了。
> 2.以前的问题可能是以下因素引起的：重建缓存没有做好。启动的config替换没有做好。重建缓存可以用一行命令行执行，config替代的时候需要彻底删除原先的colver文件，再把最新的拷贝进去。
> 3.发现外接usb扩展坞的时候，mac重启会进不去系统选择界面，win重启可以。
> 4.后续需要继续折腾usb网卡问题。
> 
> 感谢bigsadan耐心解答！

进不去选择界面， 可能是因为EFI里缓存文件之类造成的，可以尝试在WINDOWS下把一些.开头的隐藏文件删除看看。
也可以先启动系统再插USB扩展，反正都是即插即用的。

**Comment by whiteriche** [comment]
> > 我的问题已解决了。
> > 1.10.14.4升级到10.14.5，重建了缓存，用config替代了config-install启动。问题解决了。
> > 2.以前的问题可能是以下因素引起的：重建缓存没有做好。启动的config替换没有做好。重建缓存可以用一行命令行执行，config替代的时候需要彻底删除原先的colver文件，再把最新的拷贝进去。
> > 3.发现外接usb扩展坞的时候，mac重启会进不去系统选择界面，win重启可以。
> > 4.后续需要继续折腾usb网卡问题。
> > 感谢bigsadan耐心解答！
> 
> 进不去选择界面， 可能是因为EFI里缓存文件之类造成的，可以尝试在WINDOWS下把一些.开头的隐藏文件删除看看。
> 也可以先启动系统再插USB扩展，反正都是即插即用的。

OK

**Comment by whiteriche** [comment]
昨天调分辨率黑屏了。重装后建立缓存后用config启动时，在出现白苹果进度条的画面时就重启了，进不去系统了。快被玩疯了，哈哈哈。
这应该从哪块排查？

**Comment by bigsadan** [comment]
win下面删除整个CLOVER文件，重新拷贝进去， 重走一遍流程看看。。
分辨率建议只试我说明里提到的那几个。。其它的不要随意尝试。。

**Comment by whiteriche** [comment]
看这里说10.14.3比较稳定，我又去装10.14.3。但是没有成功。不管3 4 5都卡在硬盘安装时，跑十几分钟进度条那个地方，然后重启。然后就没有然后了。

colver10.14.5那个压缩包可以适配 10.14.3. 4. 5各个版本的镜像文件？

**Comment by whiteriche** [comment]
又折腾几次，把10.14.3装好了。装的时候又发现几个坑。。。
1.用的旧的文件适配镜像。
2.硬盘安装中间跑进度条时重启，摸电脑很烫。等电脑温度降低后手动重启继续安装完成。
3.用sudo kextcache -i /建立缓存。

坑:1.每次重启时都要手动关闭安全安装，否则选择进入系统界面不出现。
2.用usb hub外接机械键盘也会不弹出系统选择界面，只能拔掉用键盘时再插上。

疑问:1.我的是sp4 4g 128g配置，现在系统显示的是8g 256配置，不知道需不需要改，也不会改。
2.配置低是不是拷贝文件，硬盘安装时电脑发烫的原因。

**Comment by bigsadan** [comment]
手动关闭安全安装？？

显示8G内存，是因为config文件里手动添加内存信息，我的是8G，你可以手动改一下，或者把内存信息从config中删除。至于256的硬盘，你是在哪儿看到的？不可能128G的硬盘给你识别成256G。

10.14.5的clover文件相比一开始10.14.3的，区别在于kext和clover版本升到了最新，config中显卡信息注入和dvmt补丁作了修改，用10.14.5的文件配10.14.3的config，是能够正常运行10.14.3的。

**Comment by whiteriche** [comment]
1.升级到了10.14.5 ,内存显示正常。硬盘确实一直是128g，刚开始是看错了。
2.有时候重启进不到系统选择界面，必须进入surface uefi选择关闭安全启动才能进入，要不就是自动关机。

升级10.14.5时，硬盘安装完成后，重启跑进度条一直重启。用config-v启动居然通过了。以前一直卡在这一步，不知道是什么原因。

**Comment by bigsadan** [comment]
> 1.升级到了10.14.5 ,内存显示正常。硬盘确实一直是128g，刚开始是看错了。
> 2.安装时重启进不到系统选择界面，必须进入surface uefi选择关闭安全启动才能进入，要不就是自动关机。
> 
> 升级10.14.5时，硬盘安装完成后，重启跑进度条一直重启。用config-v启动居然通过了。以前一直卡在这一步，不知道是什么原因。

10.14.5中我己经取消了内存信息注入，所以会显示正常吧，安全启动必须关闭，这个是基本条件。

在初装/刚升级完成时，用config.plist -v 进入的话，有一定机率在未驱动显卡的情况下进入系统，可以利用进系统的机会重建缓存，重启后一般就驱动成功了。有些机友用install.plist总是重启进不了系统的情况下，可以尝试这样操作一下。
