### ISSUE TITLE
大大，10.14.6安装配置正常，安装后重启无限重启，操作过程不对？

### ISSUE THREAD

**Issue by jiangliujun** [bigsadan/surface-pro-4-hackintosh#14]
设备：surface pro 4 I5 HD520 8G 256G 版本
1、用网上“macOS Mojave 10.14.6 (18G84) 自带Clover v2.4 r5027 黑苹果原版安装镜像”制做启动U盘；
2、删除U盘原ESP\EFI\CLOVER，用“CLOVER 10.14.6.zip”解压拷贴原位置；
3、U盘引导启动，选择Config-Install.plist，-v，nv_disable=1，安装配置正常，重启后能显示新分区的“Boot maOS install from XX”图标；
4、选XX分区，同3操作，能完成"Installing on XX"过程，等15分钟左右，自动重启；
5、4分区自动变成“Boot macOS from XX”，同3操作启动或直接先择启动，无限重启。

是不是我第5步操作有问题，请帮忙，感谢感谢。

**Comment by bigsadan** [comment]
第5步的时候，用install.plist和config.plist 加上-V，两个都试试看能不能进入系统，只要能进入系统，重建一次缓存就好了。
如果都进不了的话，使用10.14.3下的旧版本sp4-install.plist再尝试一下。

**Comment by jiangliujun** [comment]
刚才又下了个10.14.5的，死得更彻底，走完第3步，第4步无法完成，就无限启了。会不会跟镜像也有关系，还是我这个目录结构不对呢？ 另外如果“重建一次缓存就好了”，是不是可以在WIN下挂载，删除相关缓存目录？我回到6用您说的方式再试下，不行得在白MAC（我的10.14.3）下做个镜像出来试试了。

**Comment by jiangliujun** [comment]
1、10.14.6按您的方法，sp4-install.plist先跑一次，再config-install.plist，现在可以进入了，显示分辨率非常高，触摸、轻触都正常。
2、用config.plist进入，似乎触摸板驱动不对了，只能移动和单击（重按），右键都不会来了。
继续看看驱动，起码能进了，谢谢。

**Comment by jiangliujun** [comment]
触摸板问题反馈：默认触摸板“轻点来点按”没钩，钩上问题完美解决，感谢大大相助。
