### ISSUE TITLE
10.14.6后屏幕不定时出现闪烁黑斑

### ISSUE THREAD

**Issue by josangmi** [bigsadan/surface-pro-4-hackintosh#17]
10.14.6后屏幕不定时出现闪烁黑斑 ，随机出现在屏幕上中下部分。 是驱动还是系统问题？ 有遇到过吗？

**Comment by bigsadan** [comment]
这个和系统、驱动都无关。。据说SP4有两种屏，三星屏和LG屏，三星屏就可能出现闪屏故障，LG屏不会出现。。

**Comment by lzw429** [comment]
10.14.6 似乎对「原彩」进行了调整，至少我发现 mbp 白苹果有闪屏现象
