### ISSUE TITLE
其他完美，外接显示屏颜色发紫

### ISSUE THREAD

**Issue by Elegantwolf** [bigsadan/surface-pro-4-hackintosh#18]
pro4，8g，256g
安装完成后一切完美
除了外接显示器的时候外接的屏幕会很严重的**发紫**
以及在设置中看不到显示器的音频输出
希望能够得到解决，谢谢。
另外，有人在mac环境下用过surface的拓展坞吗？是否可以正常使用呢？

**Comment by bigsadan** [comment]
外接显示器是用的HDMI接口？默认DP输出，可能会导致屏幕颜色问题，修改了一下config，在我机子上测试是没问题的。
[Config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/3479766/Config.plist.zip)

拓展坞我没有。。帮不了你。

**Comment by Elegantwolf** [comment]
替换后一切完美，也有了音频输出，谢谢！用的是绿联的minidp转HDMI。
