### ISSUE TITLE
Clover更新到5018后 无法识别mac启动项

### ISSUE THREAD

**Issue by ati46** [bigsadan/surface-pro-4-hackintosh#20]
linux正常识别，改回旧clover可以识别出mac启动项，mac已更新到10.14.6

**Comment by bigsadan** [comment]
最新的clover版本 好像己经解决这个问题了。

**Comment by ati46** [comment]
好的， 这个问题我在CLOVER中添加其他驱动解决，但是出现了新的问题开机卡在 Please go to https://panic.apple.com to report this panic @bigsadan

**Comment by ati46** [comment]
这个问题在安装10.14.3的时候也遇到过，后来我使用了自己的DSDT文件解决这个问题，但是电池补丁不起作用。 更新CLOVER后我使用的是大佬你提供的DSDT。 我想请问出现这个问题有好的解决办法吗？ @bigsadan

**Comment by bigsadan** [comment]
clover用不着一定更新到最新啊。本机稳定使用就行了，10.14.5的clover文件你如果使用正常的话，换回去也可以，同样适用于10.14.6。
或者你用自己的DSDT按照我教程里面自行打一遍补丁，具体的看我的贴子。
http://bbs.pcbeta.com/viewthread-1806282-1-1.html

**Comment by ati46** [comment]
好的， 谢谢 我改改试一试， 多谢大佬 @bigsadan
