### ISSUE TITLE
用根目录的文件，还是用压缩包里文件？还是配合着用？

### ISSUE THREAD

**Issue by duchengzhen** [bigsadan/surface-pro-4-hackintosh#21]
迷惑，只用压缩包里文件，安装一般就重启，无限循环；用根目录的文件也不行

**Comment by bigsadan** [comment]
只需用10.14.6的压缩包。如果无限重启，下载根目录中的sp4-install.plist，先用它配置进入系统重建缓存，再用config-install.plist进入系统重建缓存，最后用config.plist。
