### ISSUE TITLE
请教下换屏幕CPU内存后EFI还能用吗

### ISSUE THREAD

**Issue by josangmi** [bigsadan/surface-pro-4-hackintosh#24]
屏幕最近一直花屏，一热就花。所以只能换屏幕了，随便想升级下内存，谁知道CPU也只能一起升级了。问题来了，EFI还能用吗？

**Comment by bigsadan** [comment]
肯定得在现有EFI上做些调整啊。。。

**Comment by josangmi** [comment]
那就尴尬了，还没学到动手改EFI，从哪入手呢？

**Comment by bigsadan** [comment]
> 那就尴尬了，还没学到动手改EFI，从哪入手呢？

英文没问题，就去tonymac看教程，国内就去远景看各种翻译版的。。。
