### ISSUE TITLE
10.14.6使用install.plist安装成功后，重建缓存后替换config.plist在加载过程中无限重启

### ISSUE THREAD

**Issue by zqb-knight** [bigsadan/surface-pro-4-hackintosh#25]
使用install已经安装成功，也进行了重建缓存，但是替换config.plist无法使用
又换回install.plist又能使用
又尝试了10.14.5的efi，也无限重启，
是config.plist有什么问题吗？
还是我遗漏了哪些步骤？
希望解答
辛苦您了

**Comment by bigsadan** [comment]
尝试用sp4-install.plist进入，重建缓存。

**Comment by CZhike** [comment]
同样出现了上述无限重启的情况，重建缓存没用

**Comment by CZhike** [comment]
请问楼主解决了吗，怎么解决的呢

**Comment by zqb-knight** [comment]
我按照作者的方法试验了，最终没有成功。经过测试，只要使用install和sp4-install就能进去，但是分辨率很高，无法调hidpi，换回config就又进不去了，我后来放弃了。你可以问问其他人，如果解决的话，告诉我一声

**Comment by bigsadan** [comment]
-v模式下把重启前出错的代码要录屏发一下吧。

> 我按照作者的方法试验了，最终没有成功。经过测试，只要使用install和sp4-install就能进去，但是分辨率很高，无法调hidpi，换回config就又进不去了，我后来放弃了。你可以问问其他人，如果解决的话，告诉我一声

-v 模式下看看重启前出错提示的代码啊。 surface固件最好升到最新，尝试不要用我修改的DSDT文件，用自己机器的DSDT看是否能成功进入系统。

**Comment by zqb-knight** [comment]
按照作者的方法已经成功了，谢谢您了。
还有个问题是，每次重启后电脑开机特别慢，这个是什么原因呀？
