### ISSUE TITLE
教程安裝請 Installation tutorial please english 

### ISSUE THREAD

**Issue by BetweenBeltSizes** [bigsadan/surface-pro-4-hackintosh#26]
您好，我也想在Surface Pro 4上進行安裝，您能給我發送鏈接或與我一起閱讀安裝教程嗎？謝謝.

Nín hǎo, wǒ yě xiǎng zài Surface Pro 4 shàng jìnxíng ānzhuāng, nín néng gěi wǒ fāsòng liànjiē huò yǔ wǒ yīqǐ yuèdú ānzhuāng jiàochéng ma? Xièxiè.

Hello i would love to install on surface pro 4 also, could you please send me link or make a read me with tutorial on installation? thank you.

**Comment by stiven-ding** [comment]
I would like make it briefly. You will need some softwares to run on Windows: TransMac, EasyUEFI, and DiskGenius.
1. Download the macOS system and flash into your USB disk (16GB or above) with TransMac.
2. Download `CLOVER 10.14.6.zip` in this repository, and extract content inside to EFI partition with software like DiskGenius.
3. Add a boot entry with EasyUEFI, pointing to `CLOVERx64.efi` inside the `Clover` folder your just get. Don't forget to save.
4. Boot into your Surface UEFI BIOS (Power+Volume Up) and start with Clover. Note to keep your USB disk plugged in.
5. You should see Clover now. IMPORTANT: Go to Settings, switch "configs" to the one with `install`.
6. Make sure you have done the process in 5. Boot into macOS_Install.
7. After installing, switch to config without `install` stated.
All set and enjoy it.

**Comment by phongnh-dev** [comment]
How to rebuild the cache after the installation is complete? I got kernel panic when switch to config.plist

**Comment by stiven-ding** [comment]
> How to rebuild the cache after the installation is complete? I got kernel panic when switch to config.plist

Download and run Kext Utility at install config.

**Comment by phongnh-dev** [comment]
Could you explain a bit more details? Because I can't boot the mac OS, so I don't how to run Kext Utility
Thanks!

**Comment by stiven-ding** [comment]
You have to boot in macOS first to build the cache. Make sure you are using the correct version of config set and selecting install config to boot with.

Yours sincerely,
SD
________________________________

**Comment by phongnh-dev** [comment]
Let me list steps I did:

1. Create Installation USB with this https://github.com/bigsadan/surface-pro-4-hackintosh/blob/master/CLOVER%2010.14.6.zip

2. Install macOS onto Surface Pro 4 with Config-install.plist (It has 1 restart during installation)

3. After the installation finished, I can't boot to macOS (using Config.plist or Config-install.plist). I instead got kernel panic

What could I do now?

![photo_2020-04-22_15-46-10](https://user-images.githubusercontent.com/57913281/79961110-70cfd280-84b0-11ea-89b0-9dad9bf8df29.jpg)

**Comment by phongnh-dev** [comment]
Got worked by start in safe mode, rebuild cache then normal start

Thanks!
