### ISSUE TITLE
尝试了Catalina直接更新，显示被ban，贴一下verbose模式的log，不知道能不能帮上忙

### ISSUE THREAD

**Issue by Elegantwolf** [bigsadan/surface-pro-4-hackintosh#27]
![50113451385AF8CADBFD5CA121816248](https://user-images.githubusercontent.com/40517368/66405011-0e374d80-ea1c-11e9-8d67-f9325378673e.jpg)
![F8550E2A4088CF7C39F70D9ED947B949](https://user-images.githubusercontent.com/40517368/66405023-12636b00-ea1c-11e9-8c3b-56b2fe8e3d97.jpg)
花屏了拍不到详细的参数，清晰的那张是花屏前卡住的位置
clover更新到了5070，两种config文件下结果类似
使用正常使用中使用的config文件下，在非verbose模式下可以走到安装进度条的尽头，之后就卡在那里
在verbose模式下运行结果就如上图
使用install 的config文件，很快就被ban
这是我今晚尝试更新得到的结果
不知道能不能帮上什么忙

**Comment by bigsadan** [comment]
升级最新的clover，用新版的virtual smc，就不会出现禁行符号了。
除了显卡其它都能正常使用，再等等吧。。

**Comment by Elegantwolf** [comment]
> 升级最新的clover，用新版的virtual smc，就不会出现禁行符号了。
> 除了显卡其它都能正常使用，再等等吧。。

好的谢谢，了解了，，，还是再等等吧。。。。

**Comment by Elegantwolf** [comment]
更新很完美的结束了，新推送的更新也很顺利的装好了，目前没有任何问题，十分感谢！
