### ISSUE TITLE
Bluetooth doesn't work on 10.15 无法连接蓝牙设备

### ISSUE THREAD

**Issue by stiven-ding** [bigsadan/surface-pro-4-hackintosh#28]
升级 10.15 之后，使用 CSR8510 A10 就不能绑定/连接蓝牙鼠标了，不知是否是 VirtualSMC 的缘故？请问有其他推荐可用的 USB 适配器吗？

**Comment by bigsadan** [comment]
我用的就是这个。。正常连接罗技mx anywhere 2s，没有问题。

**Comment by stiven-ding** [comment]
感谢回复。

睡了一觉之后，可以绑定蓝牙鼠标了，但是不能连接。但是我发现，开机之后只要不登录账户，是可以通过鼠标开关机断开或连接的；登录之后就不可以连接了，鼠标一旦休眠就不能工作。这让我很困惑，无从下手😂。

**Comment by stiven-ding** [comment]
> 我用的就是这个。。正常连接罗技mx anywhere 2s，没有问题。

刚刚找到问题：一旦登录了 iCloud，蓝牙鼠标断连或休眠之后，就只能插拔适配器才能连接。不知道是哪个组件的问题，怀疑是 FInd My Device。
