### ISSUE TITLE
在升级后iCloud上传与下载十分缓慢（几乎没有速度）很难判断是我网络情况的问题还是系统本身bug还是其他与黑苹果相关的问题。

### ISSUE THREAD

**Issue by Elegantwolf** [bigsadan/surface-pro-4-hackintosh#29]
在升级Catalina后出现iCloud（包括iCloud网盘本身与照片应用中）下载与上传几乎毫无速度的情况；
在相同的网络环境下iPad与iPhone都很正常，同时电脑也可以正常访问iCloud网页版。
在一些网站搜索后并未发现有人汇报过类似问题，而且仅仅在与iCloud相关的事情中出现问题，正常访问网页等并不受影响，同时USB网卡驱动已经更新。
同时，很疑惑的是，在活动监测器中，相关的软件的上传与下载量皆为零。
仅与iCloud相关的软件出现过类似的无法同步的问题，如屏幕使用时间等。
也许是我更新时候出现了某些不可预测的问题？是否建议重装系统呢？
也不知道有没有人有遇到类似的问题。
谢谢各位。
另：有试过修改dns以及proxifier全局代理，梯子是美国的且网速足够看720p视频。

**Comment by Elegantwolf** [comment]
另2:在切换网络环境后就会有重新登录iCloud的弹窗出现，有时不用输入密码点继续就可以了，我已经想抹盘重装了。。。但是iCloud备份依旧没速度- -不敢抹啊

**Comment by bigsadan** [comment]
你是从10.14升级上来的吗？如果是建议全新安装，我在刚出BETA版的时候升级微软的ondrive也有类似问题，因为10.15的磁盘结构变了，所以需要重新安装指定位置。
全新安装10.15过几次，都没有碰到过这个问题。

**Comment by Elegantwolf** [comment]
> 你是从10.14升级上来的吗？如果是建议全新安装，我在刚出BETA版的时候升级微软的ondrive也有类似问题，因为10.15的磁盘结构变了，所以需要重新安装指定位置。
> 全新安装10.15过几次，都没有碰到过这个问题。

嗯...是这样的，我发现这个问题了，我已经在准备重新安装了...

**Comment by Elegantwolf** [comment]
> 你是从10.14升级上来的吗？如果是建议全新安装，我在刚出BETA版的时候升级微软的ondrive也有类似问题，因为10.15的磁盘结构变了，所以需要重新安装指定位置。
> 全新安装10.15过几次，都没有碰到过这个问题。

嗯，，还有一个问题，这个版本官方只提供了升级软件并没有提供dmg下载....而且tonymac的新版本还没出，正常制作的启动u盘又没有efi分区，想请教一下你是怎么制作安装u盘的呢？谢谢

**Comment by bigsadan** [comment]
远景论坛里很多做镜像的，随便下载一个用TransMac制作就可以了。
