### ISSUE TITLE
HD520 doesn’t work 

### ISSUE THREAD

**Issue by williamoak1988** [bigsadan/surface-pro-4-hackintosh#3]
感谢！根据您的文件 其它都好了 就是显卡无法驱动 显示为19M 不知道该如何解决

**Comment by bigsadan** [comment]
不应该，如果你用SP4-INSTALL.PLIST进去，本身就未驱动显卡，所以19M是正常的，如果你用默认的CONFIG.PLIST，理论上是能正常驱动的，如果无法驱动，应该是系统都进不去，不太可能出现能进入系统但只能显示19M。

**Comment by muxuar** [comment]
显卡驱动用multibeast安装

**Comment by whiteriche** [comment]
一样19m。怎么解决？
