### ISSUE TITLE
Problems with csrutil. Can´t disable.

### ISSUE THREAD

**Issue by Predatux** [bigsadan/surface-pro-4-hackintosh#30]
I've installed the operating system. When I tried to install Clover Bootloader, it gave me a problem that the system is mounted in read mode.
I tried to mount it in write mode with the command
mount -uw /
but I get error 77 (not allowed).
I tried to disable csrutil mode from recovery mode:
csrutil disable (tells me it has been disabled and to restart)
spctl --master-disable (ok)
mount -uw / (all correct)

Once the computer has restarted, if I run
csrutil status
He tells me he's active

Someone tells me how I can disable csrutil and keep it after a reboot?

**Comment by reggaemahn** [comment]
Have you tried using `sudo mount -uw /`?

**Comment by bigsadan** [comment]
use opencore, and set NVRAM- ADD-7C436110-AB2A-4BBB-A880-FE41995C9F82-csr-active-config value to E7030000.
