### ISSUE TITLE
VoodooI2C 引发内核崩溃

### ISSUE THREAD

**Issue by ati46** [bigsadan/surface-pro-4-hackintosh#33]
surface book 使用提供的VoodooI2C 引发内核崩溃， 我自己使用xcode编译了VoodooI2C 但是没有触摸板驱动，不能使用手势， 想问问大大能不能告知，怎么修改的VoodooI2C可以使触摸板正常工作

**Comment by ati46** [comment]
崩溃信息：https://github.com/ati46/temp/blob/master/Snipaste_2019-11-01_16-45-11.png

**Comment by bigsadan** [comment]
voodooi2c 里的pull requests。。自行研究吧
