### ISSUE TITLE
black screen  on Catalina 10.15.1 surface book 1

### ISSUE THREAD

**Issue by lgyasss** [bigsadan/surface-pro-4-hackintosh#34]
hi bigsadan
I installed catalina 10.15 following your guide and your clover efi on surfacebook1 with success, then I updated to 10.15.1 ,but system keeps rebooting
hope you will update an efi clover soon for 10.15.1
thank you so much for sharing your work , great job sir

**Comment by bigsadan** [comment]
just rebuild cache after updating...the clover files is suitable to 10.15.1
<img width="1196" alt="截屏2019-11-01下午11 30 17" src="https://user-images.githubusercontent.com/46431925/68035944-a95fd200-fcff-11e9-8a97-0c3da05f95df.png">

**Comment by bigsadan** [comment]
<img width="1136" alt="截屏2019-11-01下午11 34 45" src="https://user-images.githubusercontent.com/46431925/68036261-4589d900-fd00-11e9-84e1-90dbef290125.png">

**Comment by gityass** [comment]
thank you man for your reply i appreciate it
i changed the matchos to 10.15.1 , updating and crossing fingers 
 is there a way to make the touchpad recognized like in windows ?
