### ISSUE TITLE
Problem with clean installation Catalina 15.0.1

### ISSUE THREAD

**Issue by jaras86** [bigsadan/surface-pro-4-hackintosh#35]
Hello, could you help me? Install Catalina 15.0.1 with your clover 10.15. The installation worked completely but when trying to boot normally, The bar loads halfway and restarts. kernel panic and reboot. I can only enter with setup config.plist. Try correcting kext permissions and nothing. 
I also can't see which kernel panic is even in -v mode for the restart.

if I can solve it I will appreciate it, thank you.

**Comment by bigsadan** [comment]
you need to modify the config.plist, changed the Kexts patcher - "Disable minStolenSize patch" -  "match os" to 10.15.1

[https://user-images.githubusercontent.com/46431925/68036261-4589d900-fd00-11e9-84e1-90dbef290125.png](url)

**Comment by jaras86** [comment]
If I already tried that and the result was the same, my surface is 4gb ram and 128hdd can that be the problem? Thank you.

<img width="958" alt="Captura de pantalla 2019-11-06 a las 2 38 56" src="https://user-images.githubusercontent.com/57396562/68260868-966e3a00-003e-11ea-95bc-938c2a5bcf2b.png">

**Comment by bigsadan** [comment]
maybe that's the problem,  but if you installed 10.15 on your laptop with success,  you can also suc on 10.15.1
