### ISSUE TITLE
How to boot into recovery mode for macos Catalina 10.15 on surface pro 4?

### ISSUE THREAD

**Issue by suenhj** [bigsadan/surface-pro-4-hackintosh#37]
no keyboards press COMMAND + R could  work on my surface pro 4
anyone have ever successed close the SIP on  surface pro 4 ?

**Comment by suenhj** [comment]
without recovery mode I could not ajust the screen resolution for a larger character, the character is too small on my surface pro 4

**Comment by stiven-ding** [comment]
I remember if u wanna boot into rec mode in Hackintosh, your need to set config.plist to display recovery mode in the boot items. Try to modify that in Windows.

**Comment by suenhj** [comment]
> I remember if u wanna boot into rec mode in Hackintosh, your need to set config.plist to display recovery mode in the boot items. Try to modify that in Windows���.���

it is not work, I need close the security mode but no way to do it!

**Comment by bigsadan** [comment]
use opencore instead of clover
