### ISSUE TITLE
[已解决]升级10.15.2后SP4因panic无限重启

### ISSUE THREAD

**Issue by ZuoAoyu** [bigsadan/surface-pro-4-hackintosh#39]
因为在pcbeta看到有人在帖子里回复说成功升级10.15.2, 我也升级了. 没想到开机无限重启. -v模式显示的错误如下:

Coredump complete of kernel, dumped 399 segments, 1 threads overall uncompressed file length, compressed file length is 83588236bytes.

please go to apple to report this panic.

特来寻求帮助. 谢谢.

**Comment by ZuoAoyu** [comment]
PS: 我已在config.plist中将matchos版本号修改为10.15.2.

**Comment by ZuoAoyu** [comment]
已解决。解决方案：重装系统😂。

**Comment by chuxinshuo** [comment]
> 已解决。解决方案：重装系统😂。

重装什么版本的了？刚升级15.2，也是读条重启，-v模式也是直接重启，sp4-install.plist引导能进入，但显示字体小

**Comment by ZuoAoyu** [comment]
> > 已解决。解决方案：重装系统😂。
> 
> 重装什么版本的了？刚升级15.2，也是读条重启，-v模式也是直接重启，sp4-install.plist引导能进入，但显示字体小

重装的15.2版本。

**Comment by Tim-Siu** [comment]
请问要怎么重装呢？会影响原来数据吗？我直接从14.6升级遇到了一样的情况😂
