### ISSUE TITLE
sp4 4g 128 hd520 works perfectly!

### ISSUE THREAD

**Issue by williamoak1988** [bigsadan/surface-pro-4-hackintosh#4]
感谢大神，sp4终于用上了macos，而且还这么完美！
再次感谢！

**Comment by jodkiam** [comment]
兄台点解我的不行

**Comment by muxuar** [comment]
我安装10.14.5和1.14.3都出问题，在第一个分钟数快跑完的时候重启，然后就不安装了。不知道楼上各位是如何解决这个问题的。我的机子和你的一模一样。
