### ISSUE TITLE
10.14.6 系统内升级到 10.15.2，sp4-install.plist 字体小，configIs.plist读条重启

### ISSUE THREAD

**Issue by chuxinshuo** [bigsadan/surface-pro-4-hackintosh#41]
请问支持15.2系统吗，我是10.14.6直接升级，安装成功，启动的时候用configIs.plist启动会读条重启，-v模式看也是运行结束直接重启，sp4-install.plist 模式可以启动，但分辨率不能调整，显示字体很小，修改matchos为10.15.2也一样，请问这个clover支持15.2吗，谢谢

**Comment by ponghppp** [comment]
要用Config.plist启动

**Comment by ponghppp** [comment]
应该是支持的
我也成功安装10.15.2
要用Config.plist启动
sp4-install.plist 跟 configIs.plist 只是用来安装的时候用
用这2个plist启动是改不到分辨率的

**Comment by chuxinshuo** [comment]
> 应该是支持的
> 我也成功安装10.15.2
> 要用Config.plist 启动
> sp4-install.plist 跟 configIs.plist 只是用来安装的时候用
> 用这2个plist启动是改不到分辨率的
Config.plist启动会读条到一半多的时候重启，你是直接装的15.2还是升级安装的？

**Comment by ponghppp** [comment]
我是直接装的
