### ISSUE TITLE
macos 10.15.2 使用中突然崩溃，重启卡logo

### ISSUE THREAD

**Issue by ZuoAoyu** [bigsadan/surface-pro-4-hackintosh#44]
事发突然，太难受了。

-v模式错误描述如下：

VoodooI2CHIDDevice::MSHW0030 Request for HID descriptor failed
VoodooI2CHIDDevice::MSHW0030 Could not get HID descriptor

**Comment by ZuoAoyu** [comment]
真的是柳暗花明啊哈哈哈。刚才我查了查，出现错误的是触控板驱动，然后。。我就发现出现错误是因为，我把键盘卸了下来（朝后粘上去的）。把键盘正常贴上去后重启就正常了。为什么要把键盘拔下来朝后放置呢，是因为如果是正常的笔记本形态，我就没办法在桌子上摊开一本书了。

**Comment by DrSkilled** [comment]
请问你的键盘合盖后，开盖还可以用吗？（如果可以，可不可以发一下efi）

**Comment by ZuoAoyu** [comment]
我想你遇到的问题是：键盘盖（Type Cover）合上后重新打开，键盘能用、触控板不能用。我的也是这样，不过影响不大。抱歉帮不了你。@DrSkilled

**Comment by yencn** [comment]
> 我想你遇到的问题是：键盘盖（Type Cover）合上后重新打开，键盘能用、触控板不能用。我的也是这样，不过影响不大。抱歉帮不了你。@DrSkilled

我的合上打开触摸板不能用的话就再合上几秒再打开就好了
