### ISSUE TITLE
clover alternative

### ISSUE THREAD

**Issue by gityass** [bigsadan/surface-pro-4-hackintosh#45]
hi bigsadan
I was wondering if you can create an opencore bootloader for sp4 and surfacebook as an alternative to clover bootloader
thank you in advance

**Comment by stiven-ding** [comment]
It's not even possible man 😂

**Comment by samchugit** [comment]
why the alt is not possible. 😂

**Comment by stiven-ding** [comment]
> why the alt is not possible.

I thought it was impossible to port on an unstable bootloader when I replied, but now I would say it very practical when I see opencore powerfully 🤣 Four months can change a lot!

**Comment by samchugit** [comment]
> > why the alt is not possible.
> 
> 
> 
> I thought it was impossible to port on an unstable bootloader when I replied, but now I would say it very practical when I see opencore powerfully 🤣 Four months can change a lot!

Glad to hear that! Hope someone could port it to opencore
