### ISSUE TITLE
Surfacebook 22MB graphics

### ISSUE THREAD

**Issue by osama1551** [bigsadan/surface-pro-4-hackintosh#48]
![1580743335820265283628792816042](https://user-images.githubusercontent.com/29658987/73665474-d2e71b80-46a9-11ea-9805-a5861aba8d0e.jpg)

**Comment by stiven-ding** [comment]
try to use the "install" configuration and rebuild cache, then reboot with the regular configuration.

**Comment by osama1551** [comment]
I followed the steps and it appears to me like this [https://photos.app.goo.gl/RFrbMJgRjW9eF8ov8(url)

**Comment by osama1551** [comment]
Problem solved , thank you very very much

**Comment by basser2** [comment]
> Problem solved , thank you very very much

same with you,how did you solve the problem?
