### ISSUE TITLE
大佬，我直接安装完用那个config.plst开机，开一半重启什么情况

### ISSUE THREAD

**Issue by jodkiam** [bigsadan/surface-pro-4-hackintosh#5]
大佬，我直接安装完用那个config.plst开机，开一半重启什么情况

**Comment by bigsadan** [comment]
机型正确的话应该不会出现这种情况，确认你用sp4-install.plist完成所有安装以及设置，重建一下缓存，再用config.plist进入

**Comment by josangmi** [comment]
我也碰到了这个情况，我刚开始进到mac没有重建缓存的时候，触摸屏的右键可以，重建之后就不行了，而且不能用config.plst开机不然就一直重启，睡眠也不成功，我直接试了10.14.4，声音有了，但是很小..。现在就是睡眠不行。

**Comment by bigsadan** [comment]
10.14.4 Framebuffer有变化，whatevergreen暂未整合，所有现在的CONFIG只能用于10.14.3，等有时间升级测试好了再发布出来吧。

**Comment by josangmi** [comment]
嗯换回，10.14.3 一切非常完美。该感谢了。

**Comment by UloveMheart** [comment]
10.14.3下用config.plst进入会在条大约一半多的地方重启（加-v参数会看到 applekeystore operation failed...的错误信息然后快速的刷很多数据之后重启） 用instll sp4的config也会出现这个问题，但是有一定概率能进入，当然进入后没有显卡驱动。（Ps.我之前用10.14.4的时候也出现过这个问题）

**Comment by Predatux** [comment]
更改config.plist文件后，我无法启动系统。 我得到内核恐慌或黑屏，左上角有白色光标。 我试图用相机捕捉开始日志，但它很复杂

**Comment by muxuar** [comment]
我安装10.14.5和1.14.3都出问题，在第一个分钟数快跑完的时候重启，然后就不安装了。不知道楼上各位是如何解决这个问题的
