### ISSUE TITLE
Surface Book 升级10.15.4后使用config.plist无限重启

### ISSUE THREAD

**Issue by foodff0225** [bigsadan/surface-pro-4-hackintosh#55]
原系统10.15.2 升级过程中提示无法使用blesstool更改Startup Disk 强制重启后只有用ConfigIS才能进入系统 config Panic 重建过缓存 无果

**Comment by abccyz** [comment]
我这也试过不行的

**Comment by Tim-Siu** [comment]
同问。有大佬出一个15.4的clover吗

**Comment by gityasss** [comment]
hi all
the solution for bliss tool problem is as follows
change the default boot drive from "lastBootedvolume" to my default drive. example " CATALINA" for me
after this you will update successfully but you will get a kernel panic once you use the config.plist
we need a new modified config.plist for 10.15.4 to work properly

**Comment by foodff0225** [comment]
Exactly, I also tried a whole new installation, it didnt work. Waiting for new config.....



---原始邮件---
发件人: "gityasss"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 晚上9:17
收件人: "bigsadan/surface-pro-4-hackintosh"<surface-pro-4-hackintosh@noreply.github.com&gt;;
抄送: "foodff0225"<1782397966@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [bigsadan/surface-pro-4-hackintosh] Surface Book 升级10.15.4后使用config.plist无限重启 (#55)




 
hi all
 the solution for bliss tool problem is as follows
 change the default boot drive from "lastBootedvolume" to my default drive. example " CATALINA" for me
 after this you will update successfully but you will get a kernel panic once you use the config.plist
 we need a new modified config.plist for 10.15.4 to work properly

**Comment by qwind360** [comment]
我装10.15.3也一样，我用了网上的一个15.3的clover，但装完只能用configIs才能进，重建缓存也无效，我用的clover是网友制作的，百度网盘链接: https://pan.baidu.com/s/1ezVAM2p3EOZBHpVUZ5jXrQ 提取码: c9ik

**Comment by samchugit** [comment]
@gityasss hi, can you upload the modified config.plist or tell us how to modify it? thx!
