### ISSUE TITLE
i7 8G 256GB 花屏解决

### ISSUE THREAD

**Issue by MIracleyin** [bigsadan/surface-pro-4-hackintosh#56]
系统安装10.15后出现花屏 解决办法：将图片3位置改为 00002659
![Uploading image.png…]()

**Comment by abccyz** [comment]
图片看不了  能否重传下

**Comment by MIracleyin** [comment]
<img width="1254" alt="截屏2020-04-04下午10 57 49" src="https://user-images.githubusercontent.com/29721742/78454039-1bca4900-76c8-11ea-97ab-22f643e2d759.png">

**Comment by MIracleyin** [comment]
你好，已经更新

发件人: chenyz <notifications@github.com>
答复: bigsadan/surface-pro-4-hackintosh <reply@reply.github.com>
日期: 2020年4月4日 星期六 下午5:53
收件人: bigsadan/surface-pro-4-hackintosh <surface-pro-4-hackintosh@noreply.github.com>
抄送: Miracle Yin <miracleyin@live.com>, Author <author@noreply.github.com>
主题: Re: [bigsadan/surface-pro-4-hackintosh] i7 8G 256GB 花屏解决 (#56)


图片看不了 能否重传下

**Comment by abccyz** [comment]
看到了 谢谢 我这默认就是这个值 @MIracleyin

**Comment by gityasss** [comment]
hi all 
the solution for bliss tool problem is as follows 
change the default boot drive from "lastBootedvolume" to my default drive. example " CATALINA" for me
after this you will update successfully but you will get a kernel panic once you use the config.plist
we need a new modified config.plist for 10.15.4 to work properly

**Comment by Smileher** [comment]
您好，有个问题想请教下，sp4的i5和i7是不是装的方法和软件都一样？

**Comment by MIracleyin** [comment]
你好，方法一样，但是需要修改一些config值。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by Smileher** [comment]
您好，可否有详细的教程共参考，谢谢。


________________________________
发件人: Miracle Yin <notifications@github.com>
发送时间: Monday, April 27, 2020 11:26:41 PM
收件人: bigsadan/surface-pro-4-hackintosh <surface-pro-4-hackintosh@noreply.github.com>
抄送: ChenHe <vchenhe@live.com>; Comment <comment@noreply.github.com>
主题: Re: [bigsadan/surface-pro-4-hackintosh] i7 8G 256GB 花屏解决 (#56)


你好，方法一样，但是需要修改一些config值。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by MIracleyin** [comment]
用这个efi就可以正常安装，教程直接surface pro4 黑苹果。然后安装完成后，i7集成显卡是无法驱动成功的，需要按我的图片改数值。
建议安装版本，15.4

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by MIracleyin** [comment]
建议安装版本10.15

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by Smileher** [comment]
好嘞，我一直没敢动手，因为网上都是i5的，我一直不确定i7和i5的是不是一样的方法，等过两天网卡和备用电脑到了开干，多谢大哥。


发件人: Miracle Yin<mailto:notifications@github.com>
发送时间: 2020年4月28日 7:33
收件人: bigsadan/surface-pro-4-hackintosh<mailto:surface-pro-4-hackintosh@noreply.github.com>
抄送: ChenHe<mailto:vchenhe@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [bigsadan/surface-pro-4-hackintosh] i7 8G 256GB 花屏解决 (#56)

建议安装版本10.15

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by fsnfs** [comment]
> 系统安装10.15后出现花屏 解决办法：将图片3位置改为 00002659

00001659 or 2659 都不是SP4 i7對應的顯卡，i7不是對應00002619嗎？
