### ISSUE TITLE
Surface Pro 4更新10.15.4无法进入系统，指纹键盘盖问题

### ISSUE THREAD

**Issue by lbcz-tian** [bigsadan/surface-pro-4-hackintosh#59]
从15.3更新15.4无限重启panic，只能用`configis.plist`进系统。clover和kexts都更新了还是一样的。

我的键盘盖是带指纹的，盖上之后再打开就用不了了，也无法热插拔，大写锁定的灯也不亮。

大伙有成功安装15.4的吗？

**Comment by gityasss** [comment]
hi all
I have same problem once I updated from 10.15.3 to 10.15.4 , it gives me kernel panic 
we need a new config.list for 10.15.4 
hope bigsadan finds a solution for this issue
have a good day all

**Comment by gaopl01202** [comment]
同样问题，10.15.3没事。10.15.4就废了

**Comment by bohenao** [comment]
https://github.com/bigsadan/surface-pro-4-hackintosh/issues/64

**Comment by Predatux** [comment]
Me too...

**Comment by lbcz-tian** [comment]
@Predatux @gaopl01202 已经解决了啊，去看看别的issue，有人分享了10.15.4可用的EFI，sp4和sb1是通用的
Already solved. Check other issues, someone has shared a EFI folder and it works for 10.15.4 on both sp4 and sb1.

**Comment by Predatux** [comment]
Can you please link these folder?
