### ISSUE TITLE
surface book触摸板

### ISSUE THREAD

**Issue by violin321** [bigsadan/surface-pro-4-hackintosh#6]
请问surface book触摸板使用你的驱动，右键会失灵怎么办？

**Comment by bigsadan** [comment]
没有surface book无法帮你解决，不过有用surface book的机友使用我的EFI，和SP4一样的效果，触摸板正常，热插拔也没有问题

**Comment by violin321** [comment]
嗯嗯，那个我已经解决了，请问你配置里有网卡内建吗，应该没办法登陆app store吧？

**Comment by bigsadan** [comment]
有内建EN0的KEXT，可以登陆APP STORE及正常下载。

**Comment by violin321** [comment]
surface book电量满了一直是50%能解决吗

**Comment by bigsadan** [comment]
http://bbs.pcbeta.com/viewthread-1806282-14-1.html
没有机器，无法测试，我贴子里有surface book的机友，你可以具体和他交流。

**Comment by violin321** [comment]
上周才开始接触黑苹果，没有远景账号（手动捂脸），已经通过你的帖子学习到很多了，目测电量就是按照一半来的，10%就是20%实际电量

**Comment by bigsadan** [comment]
电量的问题，你按照rehabman的拆解教程来自行做个补丁吧，教程里不明确的地方，你可以参考我电量补丁里的实际方法。。只要仔细按着走，肯定是没什么问题的。
