### ISSUE TITLE
10.15.0 to 10.15.5 beta failed

### ISSUE THREAD

**Issue by chanip** [bigsadan/surface-pro-4-hackintosh#61]
I can update and access to the system with install.plist but not config.plist. the problem is install.plist shows words smaller and run slower. anyone can help?

**Comment by lbcz-tian** [comment]
Use a translator and take a look at those issues about upgrading to 10.15.4 then you will know nobody can help🤣
reinstall 10.15.3 and wait owner update new config.plist, good luck.
