### ISSUE TITLE
升级10.15.4后进系统黑屏

### ISSUE THREAD

**Issue by williamhx** [bigsadan/surface-pro-4-hackintosh#62]
surfacebook1用原来的config.plist在10.15.2下工作正常，但是升级10.15.4以后陷入panic，提示appleintelkblgraphicsframebuffer有问题。

于是乎我使用如下补丁：
    Comment: DVMT for AppleIntelKBLGraphicsFramebuffer﻿ (Credits DalianSky) for 10.15.x
    Name: AppleIntelKBLGraphicsFramebuffer
    Find: 0F82A703 0000
    Replace: 0F820000 0000
    MatchOS: 10.15.x
依然panic。估计之前bigsadan是将gpu做成kabylake hd620了。

然后我尝试使用skylake的补丁：
    Comment: DVMT for AppleIntelSKLGraphicsFramebuffer﻿ (Credits DalianSky) for 10.15.x
    Name: com.apple.driver.AppleIntelSKLGraphicsFramebuffer
    Find: 0F828F03 0000
    Replace: 0F820000 0000
并且用hackintool重做了HD520的缓冲帧。
这次能成功进入系统，但是显示屏只有背光没有图像，黑屏。
不知道是不是EDID的问题？还是其他显示屏内建的方法问题？

最后跪求大神继续更新～

**Comment by Ackincolor** [comment]
Amazing :)
On intel hd 520 , it's working with catalina 10.15.3
![15875629173862404336149170522645](https://user-images.githubusercontent.com/17449684/79989181-db344300-84af-11ea-8637-070eaee076b0.jpg)

**Comment by williamhx** [comment]
Updates: now my surface book 1 can work on 10.1.5.4! New patch is:
com.apple.driver.AppleIntelKBLGraphicsFramebuffer
Find: 0F828F03 0000
Replace: EB048F03 0000
Disable minStolenSize less or equal fStolenMemorySize assertion, 10.15.4

<img width="586" alt="截屏2020-04-23 下午1 53 34" src="https://user-images.githubusercontent.com/53890840/80064287-4d695e00-856a-11ea-9416-f893010ce465.png">

The next thing I'm expecting is the Brightness Auto Adjust. So far I can only manual adjust and cannot auto adjust. Looks like the SSDT-ALS0.aml did not work for me.

**Comment by gityasss** [comment]
hi William
I am updating from 10.15.3 to 10.15.5 beta 2 and will use your solution
I will keep you up if it works 
keep the good work mate

**Comment by gityasss** [comment]
updated my surface book 1 to 10.15.5 using william fix
thanks
![Screen Shot 2020-04-24 at 12 22 32](https://user-images.githubusercontent.com/63503032/80225610-d18b1680-863a-11ea-95d6-5d02c16a5092.png)

**Comment by lbcz-tian** [comment]
老哥能分享下EFI吗？我的是SP4，能直接用你的 EFI不？😂

**Comment by Tim-Siu** [comment]
> Updates: now my surface book 1 can work on 10.1.5.4! New patch is:
> com.apple.driver.AppleIntelKBLGraphicsFramebuffer
> Find: 0F828F03 0000
> Replace: EB048F03 0000
> Disable minStolenSize less or equal fStolenMemorySize assertion, 10.15.4
> 
> <img alt="截屏2020-04-23 下午1 53 34" width="586" src="https://user-images.githubusercontent.com/53890840/80064287-4d695e00-856a-11ea-9416-f893010ce465.png">
> 
> The next thing I'm expecting is the Brightness Auto Adjust. So far I can only manual adjust and cannot auto adjust. Looks like the SSDT-ALS0.aml did not work for me.

hey william, would you like to push your EFI folder to your repository. Thanks a lot!

**Comment by lbcz-tian** [comment]
老哥，我按你的做了替换，然后按小兵的教程做了缓冲帧，但是还是panic进不去15.4的系统。。

**Comment by Tim-Siu** [comment]
> updated my surface book 1 to 10.15.5 using william fix
> thanks
> ![Screen Shot 2020-04-24 at 12 22 32](https://user-images.githubusercontent.com/63503032/80225610-d18b1680-863a-11ea-95d6-5d02c16a5092.png)

Hi gityasss
I am still having panic issue using william's solution. Could you please share your efi folder with us? Thanks a lot.

**Comment by omarhaya** [comment]
> Updates: now my surface book 1 can work on 10.1.5.4! New patch is:
> com.apple.driver.AppleIntelKBLGraphicsFramebuffer
> Find: 0F828F03 0000
> Replace: EB048F03 0000
> Disable minStolenSize less or equal fStolenMemorySize assertion, 10.15.4
> 
> <img alt="截屏2020-04-23 下午1 53 34" width="586" src="https://user-images.githubusercontent.com/53890840/80064287-4d695e00-856a-11ea-9416-f893010ce465.png">
> 
> The next thing I'm expecting is the Brightness Auto Adjust. So far I can only manual adjust and cannot auto adjust. Looks like the SSDT-ALS0.aml did not work for me.

i did it on my config for surface pro 4 oon Catalina 10.15.4 but graphic card still on 19 mb >.>

**Comment by carloscarval** [comment]
> Updates: now my surface book 1 can work on 10.1.5.4! New patch is:
> com.apple.driver.AppleIntelKBLGraphicsFramebuffer
> Find: 0F828F03 0000
> Replace: EB048F03 0000
> Disable minStolenSize less or equal fStolenMemorySize assertion, 10.15.4
> 
> <img alt="截屏2020-04-23 下午1 53 34" width="586" src="https://user-images.githubusercontent.com/53890840/80064287-4d695e00-856a-11ea-9416-f893010ce465.png">
> 
> The next thing I'm expecting is the Brightness Auto Adjust. So far I can only manual adjust and cannot auto adjust. Looks like the SSDT-ALS0.aml did not work for me.

Would you mind sharing your full EFI folder? I’ve updated from 10.14.6 to 10.15.4 and it didn’t work boot(panic related to intel framework). Then, installed the 10.15.4 clean and got the same. I tried to follow your last’s steps but no success. I’m desperate and don’t know what to do anymore :/
