### ISSUE TITLE
Working SurfaceBook 10.15.4/10.15.5 Clover Folder

### ISSUE THREAD

**Issue by gityasss** [bigsadan/surface-pro-4-hackintosh#64]
Hi all 
this is my clover folder as requested for anyone having trouble to update to latest Catalina
[Clover 10.15.4.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4547171/Clover.10.15.4.zip)

**Comment by Tim-Siu** [comment]
Hi gityasss,
I changed matchos ,ran your clover on 15.4 and the graphics are awesome. But this time I cannot have multi-touch support for trackpad. Do you have issue with that?

**Comment by Tim-Siu** [comment]
> Hi gityasss,
> I changed matchos ,ran your clover on 15.4 and the graphics are awesome. But this time I cannot have multi-touch support for trackpad. Do you have issue with that?

I uploaded voodooi2c configed by bigsadan to kext/other and it's working well. Capslock light is lost, but multitouch gesture is coming back.

**Comment by lbcz-tian** [comment]
simply replacing config.plist doesn't work for surface pro 4😣trying to find out the differences

**Comment by lbcz-tian** [comment]
by replacing whole clover folder and edit matchos, surface pro4 booted successfully🤩🤩thanks bro

**Comment by basser2** [comment]
> Hi all
> this is my clover folder as requested for anyone having trouble to update to latest Catalina
> [Clover 10.15.4.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4547171/Clover.10.15.4.zip)

thanks.my surface book Enhanced works,but the HD520 is only 22MB . the display only 3000*2000，how to change that?by the way,how about the NV gtx965M?

**Comment by samchugit** [comment]
> > Hi gityasss,
> 
> > I changed matchos ,ran your clover on 15.4 and the graphics are awesome. But this time I cannot have multi-touch support for trackpad. Do you have issue with that?
> 
> 
> 
> I uploaded voodooi2c configed by bigsadan to kext/other and it's working well. Capslock light is lost, but multitouch gesture is coming back.

hi I try your method on surface pro 4. I put voodooI2C and voodooI2CHID in to kexts. But my clover even could not boot. Do you know how to fix it?

**Comment by bohenao** [comment]
> > Hi gityasss,
> > I changed matchos ,ran your clover on 15.4 and the graphics are awesome. But this time I cannot have multi-touch support for trackpad. Do you have issue with that?
> 
> I uploaded voodooi2c configed by bigsadan to kext/other and it's working well. Capslock light is lost, but multitouch gesture is coming back.

Hi Tim, I have the same laptop with you. can you tell me where you change the matchos ?

**Comment by bohenao** [comment]
> by replacing whole clover folder and edit matchos, surface pro4 booted successfully🤩🤩thanks bro

Hi, Would you please tell which **matchos** have you edit ?

**Comment by lbcz-tian** [comment]
@bohenao  use vscode or any text edit software to edit  config.plist, and search(command+f) **matchos**, change the one that starts with 10.15 to your macOS version like 10.15.4. The default matchos in the shared clover is 10.15.5.

**Comment by bohenao** [comment]
> @bohenao use vscode or any text edit software to edit config.plist, and search(command+f) **matchos**, change the one that starts with 10.15 to your macOS version like 10.15.4. The default matchos in the shared clover is 10.15.5.

Thank a lot.  did you use config.plist or surface4.plist? and have you used multibease after installation? Greatly thanks agian.

**Comment by lbcz-tian** [comment]
@bohenao  anytime you try to install macOS, including upgrade, boot with configis.plist. After installation, boot with config.plist. 
I've never used multibease. What issue you want to fix with this software?
That's what I do, and it works for me😂

**Comment by bohenao** [comment]
Installation successed with you instruction,thanks. however I have dual boot along with windows. It keeps on booting from windows.... if I choose boot from usb then I have to reconfig to surface4.plist to bootup.

**Comment by lbcz-tian** [comment]
@bohenao  copy CLOVER folder from usb/EFI to SYSTEM/EFI on your ssd. Then use  **Bootice** software to create a boot option named CLOVER. Then you can change boot option to CLOVER in UEFI or in Bootice. Better google how to use bootice to create a boot option. Good luck

**Comment by bohenao** [comment]
@lbcz-tian Thanks!will try!

**Comment by bohenao** [comment]
@lbcz-tian Have to trouble you again everything is okay now except the touchpad multitouch (trackpad is not available in system). How did you resolve this problem? I use voodooi2c and voodooHID which were copied to /Library/Extensions but didn't work.
Thanks!

**Comment by lbcz-tian** [comment]
@bohenao copy those two kexts to EFI/CLOVER/kexts/other, and then `sudo kextcache -i /` in terminal. don't forget to delete them from /L/E. After a reboot(maybe not), touchpad should be fine.

**Comment by bohenao** [comment]
@lbcz-tian you legend! It is now working like charm!

**Comment by lbcz-tian** [comment]
@bohenao 😂😂just some tricks that beginners are not familiar with. I've been there too.
Enjoy your hackintosh bro😄

**Comment by bohenao** [comment]
@lbcz-tian do you have docking station for you surface p4 ? usb port and ethernet port are not working on my one. I did not find a suitable genericUSBXHCI.kext for it.

**Comment by bocajoe** [comment]
Amazing! I have a Surface Pro 5 with the i7, 8gb ram. Would this work?

**Comment by theailer** [comment]
> 
> 
> Hi all
> this is my clover folder as requested for anyone having trouble to update to latest Catalina
> [Clover 10.15.4.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4547171/Clover.10.15.4.zip)

You are my hero.

**Comment by huskytech9** [comment]
I am stuck and need help for my surface-to 4 i7 256 GB

**Comment by huskytech9** [comment]
I need to fix my graphics , very small graphics. does the above 15.4 folder works for 10.15.5 or 10.14.6 ?
