### ISSUE TITLE
Surface Pro 4: Catalina very high resolution

### ISSUE THREAD

**Issue by wernervp** [bigsadan/surface-pro-4-hackintosh#68]
First of all, thank you for your hard work!

I tried installing Catalina 10.15.4 with you config, and installing works with some issues which you dit not seem to have:
- it is not clear how to boot from the internal drive instead of the USB install disk
- the Intel graphics driver does not load, I get the following message: Graphics Driver failed to Load: could not register with frame buffer driver. So graphics are slow and very small.

Also there is no network connection. For WiFi this is known, but if I connect to the Surface Dock it also does not have connection, does this need a specific driver?

Hope you can help me!

**Comment by carloscarval** [comment]
Hey, about the graphics problem, you have to apply frame buffer patchs, i did successfully using this issue:
https://github.com/bigsadan/surface-pro-4-hackintosh/issues/62

About he surface dock, no idea, but if you want you can access the web using an iphone tethered.

**Comment by bohenao** [comment]
Dock is not working except the display port. (USB issuses I think)

**Comment by wernervp** [comment]
> Hey, about the graphics problem, you have to apply frame buffer patchs, i did successfully using this issue:
> #62
> 
> About he surface dock, no idea, but if you want you can access the web using an iphone tethered.

Thanks for the iPhone tip.. that does give me internet :).

I will dive into the patching, the first steps i tried did not do anything for me unfortunately. I will probably read some more about the patching and how it works.

**Comment by wernervp** [comment]
> Dock is not working except the display port. (USB issuses I think)

Ok, I assumed that was the issue indeed. But this is fixable with some USB device to get a network connection.

**Comment by Predatux** [comment]
> Hey, about the graphics problem, you have to apply frame buffer patchs, i did successfully using this issue:
> #62
> 
> About he surface dock, no idea, but if you want you can access the web using an iphone tethered.


I have a Surface Pro 4. I can't get video output after installation using config.plist, although HDMI output to external monitor works.
Which of the patches you indicate have you used? There are several in the post.
Apart from the patch, have you selected any options in the entry? Could you specify? Thank you
