### ISSUE TITLE
Kernel Panic after change Install config.plist for the final config.plist

### ISSUE THREAD

**Issue by Predatux** [bigsadan/surface-pro-4-hackintosh#7]
I have made a correct installation with version 10.14.3 and another with 10.14.4.  The installation is correct with both, but at the time of changing the installation config.plist file by the end, I get panic kernel + system reboot.  Any solution?

**Comment by bigsadan** [comment]
10.14.4 is not support yet,  install 10.14.3 and use all my clover files .

**Comment by Predatux** [comment]
thanks for the reply.  I have installed 10.14.3 and have used only your configuration files.  the installation is correct.  when I finish installing, and change the config.list file is when I have kernel panic and reboot

**Comment by Predatux** [comment]
Do you need any crash log?

**Comment by Predatux** [comment]
hello, I've been thinking about it, and looking at the boot logs, I've been told it may be a problem with my screen.
It turns out that I had to change the screen of the Surface, and they tell me that may be the problem.
I attach the start logs and the ACPI.
Thank you in advance.
[ACPI-Surface.zip](https://github.com/bigsadan/surface-pro-4-hackintosh-10.14.3/files/3250892/ACPI-Surface.zip)

**Comment by bigsadan** [comment]
no logs attached...

**Comment by Predatux** [comment]
[Error.zip](https://github.com/bigsadan/surface-pro-4-hackintosh-10.14.3/files/3290258/Error.zip)

**Comment by Predatux** [comment]
Sorry, here are the screenshots

**Comment by bigsadan** [comment]
can not get useful information from your log, did you really installed successfully?  that means u can boot into mojave by  sp4-install.plist without panic.

**Comment by Predatux** [comment]
thanks, you can help.  I have managed to install the system without problems.  Once installed, I reload the cache and change the installation config.plist to the final config.plist.  reload cache again and restart.  When you start the system the black screen remains, with a white cursor on the top left of the screen.  both the screen and the hard disk are not the originals of the surface.  trying to start the safe mode I had some Kernel panic

**Comment by bigsadan** [comment]
It doesn’t make sense,   u can boot successfully with sp4-install.plist,  it means that everything else works except Graphics card. the final config.plist only added graphics drive.
"When you start the system the black screen remains, with a white cursor on the top left of the screen",  black screen appears after process bar?  
it may caused by the Internal Display u changed,  inject your new display edid by clover and try again..

**Comment by Predatux** [comment]
Thanks for the help. Could you please explain to me how to do it? I would be grateful

**Comment by Predatux** [comment]
Solved, that was the problem.
Thank you
