### ISSUE TITLE
surface pro 4 update 10.15.5 blackout and looboot 使用OC5.8.0 macos10.15.5黑屏重启

### ISSUE THREAD

**Issue by samchugit** [bigsadan/surface-pro-4-hackintosh#71]
surface pro 4使用OC5.8.0，升级macos10.15.5，重建缓存后启动黑屏重启，已经修改config里面的framebuffer

surface pro 4 updating macos 10.15.5 blackout and reboot, using oc5.8.0, and already modified framebuffer in config.plist

**Comment by chuxinshuo** [comment]
我也遇到这样的问题，请问解决了吗

**Comment by samchugit** [comment]
> 我也遇到这样的问题，请问解决了吗

现在还没有

**Comment by chuxinshuo** [comment]
刚刚弄好，你看一下是不是没改成19.5.0，我一开始是在 Clover Contigurator 修改，保存退出再看还是19.4，所以我用文本编辑器打开修改保存，重建缓存，重启可以正常进入系统了

**Comment by samchugit** [comment]
> 刚刚弄好，你看一下是不是没改成19.5.0，我一开始是在 Clover Contigurator 修改，保存退出再看还是19.4，所以我用文本编辑器打开修改保存，重建缓存，重启可以正常进入系统了

你是升级的吗，我已经修改了19.5.0，还是会出现这种情况

**Comment by chuxinshuo** [comment]
> > 刚刚弄好，你看一下是不是没改成19.5.0，我一开始是在 Clover Contigurator 修改，保存退出再看还是19.4，所以我用文本编辑器打开修改保存，重建缓存，重启可以正常进入系统了
>

> > 刚刚弄好，你看一下是不是没改成19.5.0，我一开始是在 Clover Contigurator 修改，保存退出再看还是19.4，所以我用文本编辑器打开修改保存，重建缓存，重启可以正常进入系统了
> 
> 你是升级的吗，我已经修改了19.5.0，还是会出现这种情况

是升级的，现在正常使用

**Comment by samchugit** [comment]
> 是升级的，现在正常使用

刚试了一下，还是不行，我下载的zip，吧里面的东西全部拷贝到efi，删除了clover，然后修改config，使用install config 开机重建缓存，在开机还是不停重启

![image](https://user-images.githubusercontent.com/27361279/83101516-134d2800-a0e5-11ea-9cda-4032d4f1d551.jpeg)
这是最后捕捉到的信息

**Comment by chuxinshuo** [comment]
> > 是升级的，现在正常使用
> 
> 刚试了一下，还是不行，我下载的zip，吧里面的东西全部拷贝到efi，删除了clover，然后修改config，使用install config 开机重建缓存，在开机还是不停重启
> 
> ![image](https://user-images.githubusercontent.com/27361279/83101516-134d2800-a0e5-11ea-9cda-4032d4f1d551.jpeg)
> 这是最后捕捉到的信息

看你下你efi目录？

**Comment by samchugit** [comment]
> 看一下你EFI目录？

![image](https://user-images.githubusercontent.com/27361279/83136379-f2eb9080-a119-11ea-9dc0-4f02934b3309.png)
EFI文件夹
![image](https://user-images.githubusercontent.com/27361279/83136398-fc74f880-a119-11ea-91cc-7a5eeaea3be1.png)
OC文件夹
![image](https://user-images.githubusercontent.com/27361279/83136448-14e51300-a11a-11ea-8db8-e055b88eafad.png)
config修改的地方

**Comment by samchugit** [comment]
是因为我用的clover安装的mac然后换成OC的原因吗

**Comment by omarhaya** [comment]
I have the same problem with oc on Catalina 10.15.4

**Comment by samchugit** [comment]
> I have the same problem with oc on Catalina 10.15.4

It’s wired. I switch to clover and downgrade to 10.15.4. It show the same problem. I cannot figure why

**Comment by omarhaya** [comment]
I think there is a problem with ssdt

**Comment by omarhaya** [comment]
> > I have the same problem with oc on Catalina 10.15.4
> 
> It’s wired. I switch to clover and downgrade to 10.15.4. It show the same problem. I cannot figure why

I solved it imediatly after update u have to clear kext cache on install sp4 config on clover then restart and open with open core ( now im running all on 10.15.5)

**Comment by samchugit** [comment]
> I solved it imediatly after update u have to clear kext cache on install sp4 config on clover then restart and open with open core ( now im running all on 10.15.5)

you say clear kext cache, did you mean use kext utility to rebuild cache? 'cause it's how i did, but failed booting

**Comment by omarhaya** [comment]
> > I solved it imediatly after update u have to clear kext cache on install sp4 config on clover then restart and open with open core ( now im running all on 10.15.5)
> 
> you say clear kext cache, did you mean use kext utility to rebuild cache? 'cause it's how i did, but failed booting

I used kext updater clear kext cache on /S /L /E ( booting through clover on installer config) then i deleted clover and replaced it with opencore files then restart and all booted fine

**Comment by samchugit** [comment]
Did you guys meet ‘bless tool was unable to set the current boot disk’ when updating?

**Comment by omarhaya** [comment]
> Did you guys meet ‘bless tool was unable to set the current boot disk’ when updating?

Yah just ignore it and restart then repair kextcache with kext updater then run with OC

**Comment by chuxinshuo** [comment]
> 是因为我用的clover安装的mac然后换成OC的原因吗

我也是clover安装，然后换成OC，不太清楚你的原因了，而且看你是双系统？我的EFI只有APPLE，BOOT，OC三个文件夹

**Comment by samchugit** [comment]
hey guys, it’s solved. But I do not know how and why. Maybe kext updater helped me
