### ISSUE TITLE
亮度不能保存

### ISSUE THREAD

**Issue by gaopl01202** [bigsadan/surface-pro-4-hackintosh#72]
每次重启，亮度都会变成最大，不能保存上一次都亮度

**Comment by bigsadan** [comment]
https://dortania.github.io/OpenCore-Desktop-Guide/post-install/nvram.html

**Comment by gaopl01202** [comment]
> https://dortania.github.io/OpenCore-Desktop-Guide/post-install/nvram.html

sp4 i5 256版本
https://github.com/bigsadan/surface-pro-4-hackintosh/issues/72#issuecomment-635688946

**Comment by gaopl01202** [comment]
> https://dortania.github.io/OpenCore-Desktop-Guide/post-install/nvram.html

sp4 i5 256版本

**Comment by gaopl01202** [comment]
> https://dortania.github.io/OpenCore-Desktop-Guide/post-install/nvram.html


nvram: Error clearing firmware variables: (iokit/common) not permitted
![image](https://user-images.githubusercontent.com/12228354/83215378-654f8580-a199-11ea-9bbb-63973933232e.png)

求支援

**Comment by gaopl01202** [comment]
买了个白苹果，不折腾了
