### ISSUE TITLE
10.14.6pro4外接显示器minidp转hdmi屏幕发紫，有的显示器会有的不会，是系统问题吗

### ISSUE THREAD

**Issue by Ian-Shu** [bigsadan/surface-pro-4-hackintosh#74]
转接2k显示器发紫，拿电视做测试也发紫，都走的hdmi口；但是一个1080p显示器不会。大家有遇到类似现象吗，是转接器问题还是系统驱动问题啊

**Comment by bigsadan** [comment]
你是否用的老的clover文件？以前的config默认为DP口，新的都是hdmi，或者手动修改framebuffer-con1-type属性为hdmi值

**Comment by Ian-Shu** [comment]
您好我使用的是10.14.6您开源的clover文件，请问是10.15就更新为hdmi了吗，那我试试，多谢大佬开源

**Comment by bigsadan** [comment]
你如果10.14.6使用稳定的话，可以不变动，只需要将10.15后的config.plist中framebuffer-con1-type值替换掉你现有config中的值即可。

**Comment by Ian-Shu** [comment]
升级至10.15.x后问题已解决，谢谢！
