### ISSUE TITLE
New 10.15.5 Update keep stucking on vodooi2c on booting 

### ISSUE THREAD

**Issue by omarhaya** [bigsadan/surface-pro-4-hackintosh#75]
Hi i just installed the new files and thank you very much for your efforts but I keep restarting after stucking on this how to bypass it ?
![76179881-2876-41CA-B6F0-EF40EB0F4DD9](https://user-images.githubusercontent.com/64192471/83497514-43b90b80-a4c3-11ea-863e-b10524fcf671.jpeg)

**Comment by omarhaya** [comment]
Btw i was waiting for this for many days thanks alot

**Comment by williamhx** [comment]
I'm facing the same issue, using SurfaceBook1.

**Comment by bigsadan** [comment]
[config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4720471/config.plist.zip)
Try this...

**Comment by omarhaya** [comment]
> [config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4720471/config.plist.zip)
> Try this...

Same error , im booting from usb could it cause the problem? And I couldn’t update through oc  i used clover to update the system

**Comment by williamhx** [comment]
Me too. The new config file cannot help me to pass the stucking...

**Comment by bigsadan** [comment]
> > [config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4720471/config.plist.zip)
> > Try this...
> 
> Same error , im booting from usb could it cause the problem? And I couldn’t update through oc i used clover to update the system

it cause by smcbattery,  use acpibattery instead will be ok..

[config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4733687/config.plist.zip)

**Comment by williamhx** [comment]
> > > [config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4720471/config.plist.zip)
> > > Try this...
> > 
> > 
> > Same error , im booting from usb could it cause the problem? And I couldn’t update through oc i used clover to update the system
> 
> it cause by smcbattery, use acpibattery instead will be ok..
> 
> [config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4733687/config.plist.zip)

Tested with success! Thanks man!

**Comment by omarhaya** [comment]
> > > [config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4720471/config.plist.zip)
> > > Try this...
> > 
> > 
> > Same error , im booting from usb could it cause the problem? And I couldn’t update through oc i used clover to update the system
> 
> it cause by smcbattery, use acpibattery instead will be ok..
> 
> [config.plist.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/4733687/config.plist.zip)

it works now but when system goes to sleep it gets buggy (sleeps automatically and drain battery)

**Comment by fsnfs** [comment]
我的也一樣，下載來試試看

**Comment by fsnfs** [comment]
成功了，謝謝！

**Comment by omarhaya** [comment]
fixed
