### ISSUE TITLE
Steps to Install for SurfacePro4

### ISSUE THREAD

**Issue by huskytech9** [bigsadan/surface-pro-4-hackintosh#78]
Hi Team, I am struggling installing Catalina 10.15.5 on my surface pro 4. I have spend 1 week and could not pass apple logo during first boot.
Anyone one available to help to get it done.
I do not find complete steps. Please help

**Comment by huskyiptv** [comment]
![7370A885-C480-4FF1-A3CD-30B8C6DB1B32](https://user-images.githubusercontent.com/63915924/84342595-f64c3680-ab73-11ea-95cf-e729da715f04.jpeg)

**Comment by omarhaya** [comment]
picture is not clear what the message says?

**Comment by huskyiptv** [comment]
_It says error occurred while preparing the installation. Please try application later___ 
I have retried all the steps, not sure what I am missing here

**Comment by bigsadan** [comment]
try another install img...

**Comment by huskyiptv** [comment]
Hi Thank . could you please explain more in detail.

**Comment by omarhaya** [comment]
> Hi Thank . could you please explain more in detail.

Try down loading olarila image

**Comment by huskyiptv** [comment]
Thanks I did that. I got black screen after select from clover

**Comment by huskyiptv** [comment]
Seems no here to help

**Comment by huskytech9** [comment]
Switched to opencore/10.15.5 and able to install.
Closing this thread
