### ISSUE TITLE
Surface Book: Displays not identified until plugged again after 10.15.5 update

### ISSUE THREAD

**Issue by stiven-ding** [bigsadan/surface-pro-4-hackintosh#82]
Surface Book 升级 10.15.5 后（opencore 引导），开机时连接的外接显示器无法识别，只能热插拔一次才显示。电脑合盖休眠后，再唤醒也无法识别外接显示器。

**Comment by stiven-ding** [comment]
Possible solution:
https://github.com/acidanthera/bugtracker/issues/783

**Comment by basser2** [comment]
> Surface Book 升级 10.15.5 后（opencore 引导），开机时连接的外接显示器无法识别，只能热插拔一次才显示。电脑合盖休眠后，再唤醒也无法识别外接显示器。

请问下你是那版本的？我的i7增强版Intel520 的显卡一直只有22M 可以分享一下文件吗？

**Comment by stiven-ding** [comment]
Adding boot arg "agdpmod=vit9696,pikera" solves this problem

启动参数加入 agdpmod=vit9696,pikera，问题解决
