### ISSUE TITLE
Very small graphics ( Mojave 10.14.6 )

### ISSUE THREAD

**Issue by huskytech9** [bigsadan/surface-pro-4-hackintosh#84]
Hi I installed 10.14.6 Mojave
My fonts are too small
Surface Pro 4 / i7 /256 GB
Any one here to help me how to fix the resolution

**Comment by theailer** [comment]
I also have this issue(not able to use scaling) and it seems as macos is not using hardware acceleration for the igpu.

**Comment by theailer** [comment]
Actually got it working perfectly using clover and this link:
https://github.com/bigsadan/surface-pro-4-hackintosh/issues/64

**Comment by huskytech9** [comment]
Thanks for reply.
Could you confirm if following things are working
Battery percentage 
Headphone jack
Camera

**Comment by huskytech9** [comment]
> Actually got it working perfectly using clover and this link:
> #64

There are three plist. I used all for them for install , two of them did not work and sp4 install config says try again later

**Comment by theailer** [comment]
Ah, I was under the impression that you already had a working installed mac os.
Can confirm that battery percentage works but the camera is not detected. Have not yet tried the headphone jack.

**Comment by theailer** [comment]
I installed 10.15.5 with a full install, ie not the internet installer.

**Comment by huskytech9** [comment]
thanks for reply. I am using Mojave 10.14.6 with i7 /256 GB and only showing 19 MB graphics.
could you please confirm which Clover folder you are using, when I am using above clover you mentioned, I am getting error installing catalina after almost 90 % saying unable to install. please try again later

**Comment by huskytech9** [comment]
Worked with open core 10.15.5
