### ISSUE TITLE
Install/Restore BigSur with Clover

### ISSUE THREAD

**Issue by gityasss** [bigsadan/surface-pro-4-hackintosh#85]
for those who want to test macos bigsur on their surface pro 4/ surface book ... enjoy !
https://www.olarila.com/topic/9063-guide-installrestore-bigsur-with-clover/

**Comment by you-ui** [comment]
Hi, did this end up working for you? If so would you post your EFI? Thanks

**Comment by gityasss** [comment]
nope i tried but didnt work for me
waiting for Bigsadan to update files for macos big sur

**Comment by WONGWAI1017** [comment]
> for those who want to test macos bigsur on their surface pro 4/ surface book ... enjoy !
> https://www.olarila.com/topic/9063-guide-installrestore-bigsur-with-clover/

Can I get a fully working Big Sur EFI folder for Surface from you by any chance?
