### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by huskytech9** [bigsadan/surface-pro-4-hackintosh#87]
Error while installing 10.15.5. Tried different usb but same result. Any idea what Iam doing wrong

![F5DBFA00-6CEC-466A-BE9C-2CD3218A2541](https://user-images.githubusercontent.com/63915924/87226628-0b7ad780-c363-11ea-8525-da2afe367d18.jpeg)

**Comment by CLegendQ** [comment]
Use OpenCore and install with https://github.com/bigsadan/surface-pro-4-hackintosh/blob/master/10.15.4/configInstall/config.plist

**Comment by huskytech9** [comment]
Thanks for replying when I use open core . I only see nvram option, nothing else. I use recovery mac os with open core

**Comment by huskytech9** [comment]
Success ! I was able to install with open core , Mac OS 10.15.5. Working great so far. 
Things confirmed working
1. Graphics
2. Headphone jack
3. usb jack
4. Sound
5. wifi ( working with usb hub. I am using TP Link slim USB adapter )

things not working
1. Track pad double click and drag and drop sometimes do not work
2. Camera
3. Inbuilt wifi
<img width="1266" alt="Screen Shot 2020-07-12 at 1 33 54 PM" src="https://user-images.githubusercontent.com/63915924/87256351-97b1fb00-c446-11ea-8daf-b2746ec8fc89.png">

**Comment by omarhaya** [comment]
> Success ! I was able to install with open core , Mac OS 10.15.5. Working great so far.
> Things confirmed working
> 
> 1. Graphics
> 2. Headphone jack
> 3. usb jack
> 4. Sound
> 5. wifi ( working with usb hub. I am using TP Link slim USB adapter )
> 
> things not working
> 
> 1. Track pad double click and drag and drop sometimes do not work
> 2. Camera
> 3. Inbuilt wifi
> 
> <img alt="Screen Shot 2020-07-12 at 1 33 54 PM" width="1266" src="https://user-images.githubusercontent.com/63915924/87256351-97b1fb00-c446-11ea-8daf-b2746ec8fc89.png">

just disable pressure touch on tackled setting and it will work perfectly

**Comment by huskytech9** [comment]
* iMessage does not work said try again later

**Comment by omarhaya** [comment]
> * iMessage does not work said try again later

u need to install nullethernet kext and make wifi as en0 network adapter

**Comment by huskytech9** [comment]
can i use clover configurator or have to be with open core ?
