### ISSUE TITLE
iMessage / Opencore / 10.15.5

### ISSUE THREAD

**Issue by huskytech9** [bigsadan/surface-pro-4-hackintosh#88]
I Installed catalina 10.15.5 with open core and use this for install 
https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/10.15.4/configInstall

and then i rebuild cache and use this for normal use
https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/10.15.5

Issue :- iMessage keeps saying unable to contact activation server, although I logged into iCloud. 
<img width="465" alt="Screen Shot 2020-07-12 at 5 14 52 PM" src="https://user-images.githubusercontent.com/63915924/87256858-1f5a3280-c464-11ea-9818-c03441fc5dcb.png">

**Comment by omarhaya** [comment]
> I Installed catalina 10.15.5 with open core and use this for install
> https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/10.15.4/configInstall
> 
> and then i rebuild cache and use this for normal use
> https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/10.15.5
> 
> Issue :- iMessage keeps saying unable to contact activation server, although I logged into iCloud.
> <img alt="Screen Shot 2020-07-12 at 5 14 52 PM" width="465" src="https://user-images.githubusercontent.com/63915924/87256858-1f5a3280-c464-11ea-9818-c03441fc5dcb.png">

u need to install nullethernet kext and change wifi usb dongle to en0 check for how to in google

**Comment by huskytech9** [comment]
can I clover configurator or have to be open core

**Comment by omarhaya** [comment]
> can I clover configurator or have to be open core

Use propertree and search for a guide on how to install nullethernetkext

**Comment by huskytech9** [comment]
No idea sir how to do that. I will have to spend more time on this. :(

**Comment by omarhaya** [comment]
> No idea sir how to do that. I will have to spend more time on this. :(

https://victorgamer0720yt.gitbook.io/hackintosh-imessage-fixup/lets-get-this-to-work.

**Comment by huskytech9** [comment]
It says page not found
![B398F4CF-F1A0-4C71-BBB6-F61ED3D10D3D](https://user-images.githubusercontent.com/63915924/87258635-1755bf00-c473-11ea-8177-f0ba07dd3905.jpeg)

**Comment by omarhaya** [comment]
sorry this should work https://victorgamer0720yt.gitbook.io/hackintosh-imessage-fixup/

**Comment by huskytech9** [comment]
Thanks. I followed the instructions to copy nullethernet to my efi folders but no joy. 
I think kext of null ethernet no showing. Not sure where to go from there. My apple store is working fine only issue with iMessage

**Comment by huskytech9** [comment]
I unable to enable as built in after injecting nullethernet.
I followed instructions carefully but no joy.


<img width="609" alt="Screen Shot 2020-07-13 at 10 24 41 PM" src="https://user-images.githubusercontent.com/63915924/87378142-2f087280-c55b-11ea-8f0e-c15558c269cf.png">

**Comment by omarhaya** [comment]
> I unable to enable as built in after injecting nullethernet.
> I followed instructions carefully but no joy.
> 
> <img alt="Screen Shot 2020-07-13 at 10 24 41 PM" width="609" src="https://user-images.githubusercontent.com/63915924/87378142-2f087280-c55b-11ea-8f0e-c15558c269cf.png">

 U need to end like this 
Nullethernet en1
Your wifi dongle en0 
![image](https://user-images.githubusercontent.com/64192471/87400800-f2bc2d00-c5c1-11ea-83dc-9ad07d40328f.jpg)

**Comment by huskytech9** [comment]
Do not know looks like nullethernet I have does not work with my model

**Comment by omarhaya** [comment]
> Do not know looks like nullethernet I have does not work with my model

Nope u have to make some dsdt files true in config PNLF.anl i think u have to activate it to make it work

**Comment by huskytech9** [comment]
thanks. how i can .anl files.
also can you confirm, do I need to remove original nullethernet kext after copy new one

**Comment by huskytech9** [comment]
I got patch txt to enable . could you please help how to enable with txt

**Comment by huskytech9** [comment]
PNLG is already set to TRUE

<img width="818" alt="Screen Shot 2020-07-14 at 11 35 33 PM" src="https://user-images.githubusercontent.com/63915924/87500630-f768fb80-c62a-11ea-8179-9a4498d194d5.png">

**Comment by omarhaya** [comment]
> PNLG is already set to TRUE
> 
> <img alt="Screen Shot 2020-07-14 at 11 35 33 PM" width="818" src="https://user-images.githubusercontent.com/63915924/87500630-f768fb80-c62a-11ea-8179-9a4498d194d5.png">

Dude i was mistaken it was rmne.dsdt u have ti add it first to config then set it to true

**Comment by huskytech9** [comment]
Awesome ! I made it . Thank you
