### ISSUE TITLE
surface 4 从macOS 10.15.5升级到10.15.6后无限重启

### ISSUE THREAD

**Issue by chuxinshuo** [bigsadan/surface-pro-4-hackintosh#96]
10.15.5的时候用的是oc引导，最新版，升级到10.15.6之后引导无限重启，进不了系统，可以用安装版 config.plist 进入系统，但内核重建换回完整版就无限重启，也换过别的版本的clover，也都是一样的问题，安装模式可以，完整版就进不去，有遇到类似问题吗

**Comment by WONGWAI1017** [comment]
一样的问题，你找到解决方法了吗？

**Comment by WONGWAI1017** [comment]
> 10.15.5的时候用的是oc引导，最新版，升级到10.15.6之后引导无限重启，进不了系统，可以用安装版 config.plist 进入系统，但内核重建换回完整版就无限重启，也换过别的版本的clover，也都是一样的问题，安装模式可以，完整版就进不去，有遇到类似问题吗

一样的问题，你找到解决方法了吗？

**Comment by chuxinshuo** [comment]
> > 10.15.5的时候用的是oc引导，最新版，升级到10.15.6之后引导无限重启，进不了系统，可以用安装版 config.plist 进入系统，但内核重建换回完整版就无限重启，也换过别的版本的clover，也都是一样的问题，安装模式可以，完整版就进不去，有遇到类似问题吗
> 
> 一样的问题，你找到解决方法了吗？

还没有，一直是这样

**Comment by chuxinshuo** [comment]
都没有升级10.15.16吗？还是就我遇见这样的问题。。

**Comment by omarhaya** [comment]
this is my EFI which supports 10.15.6 Catalina and no more tackpad not working after opening the led after sleep also all kexts are up to date and work perfectly and surface dock now almost fully supported (except for the sound couldn't figure that out yet ) also iMessage works fine just change the serial number for your own ,and if u need any help I'm glad to help.
[
[EFI SP4 10.15.6.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/5001499/EFI.SP4.10.15.6.zip)
](url)

**Comment by chuxinshuo** [comment]
> 这是我的EFI，它支持10.15.6卡塔琳娜（Catalina），并且在打开LED睡眠后不再有钉板不起作用，而且所有kexts都是最新的并且可以正常工作，并且水面扩展坞现在几乎得到了完全支持（除了声音无法说明这一点） ）而且iMessage也可以正常工作，只需为您自己更改序列号，如果您需要任何帮助，我们很乐意为您提供帮助。
> [
> [EFI SP4 10.15.6.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/5001499/EFI.SP4.10.15.6.zip)
> ]（URL）
Just finished it, it can be used normally, thank you

> 这是我的EFI，它支持10.15.6卡塔琳娜（Catalina），并且在打开LED睡眠后不再有钉板不起作用，而且所有kexts都是最新的并且可以正常工作，并且水面扩展坞现在几乎得到了完全支持（除了声音无法说明这一点） ）而且iMessage也可以正常工作，只需为您自己更改序列号，如果您需要任何帮助，我们很乐意为您提供帮助。
> [
> [EFI SP4 10.15.6.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/5001499/EFI.SP4.10.15.6.zip)
> ]（URL）
finished it, it can be used normally, thank you very much

**Comment by omarhaya** [comment]
welcome

**Comment by omarhaya** [comment]
[EFI OC SP4 10.15.6.zip](https://github.com/bigsadan/surface-pro-4-hackintosh/files/5008166/EFI.OC.SP4.10.15.6.zip)
 sorry this is the one with the LED opening wakeup fix

**Comment by xc9253** [comment]
安装10.15.6安装代码重启 ，图上的文件 我用了怎么没有用啊
