### ISSUE TITLE
外接显示屏，然后笔记本就黑屏，偶尔行偶尔不行，现在数据线拔下也是黑屏，大佬们怎么解决？i7 版本的surface

### ISSUE THREAD

**Issue by cassano0409** [bigsadan/surface-pro-4-hackintosh#98]
外接显示屏，然后笔记本就黑屏，偶尔行偶尔不行，现在数据线拔下也是黑屏，大佬们怎么解决？

**Comment by bohenao** [comment]
Can you use "gather windows" to see what happens to what happens to laptop display?
or Install HiDPI to change setting ?
